### ISSUE TITLE
Perform backup from a standby/recovery node?

### ISSUE THREAD

**Issue by miketheman** [wal-e/wal-e#111]
I was under the impression that since we already have a master-standby replication going on,we could use WAL-E to perform a "full" backup from a standby, to prevent any kind of i/o or other performance degradation on the master.

However when performing a backup-push, I get:

``` console
$ PGPORT=5433 /usr/bin/envdir /etc/wal-e /usr/local/bin/wal-e backup-push /data/postgres/9.3/my_cluster
ERROR:  recovery is in progress
HINT:  WAL control functions cannot be executed during recovery.
wal_e.operator.backup WARNING  MSG: blocking on sending WAL segments
        DETAIL: The backup was not completed successfully, but we have to wait anyway.  See README: TODO about pg_cancel_backup
        STRUCTURED: time=2014-05-05T22:21:49.796014-00 pid=8763
ERROR:  recovery is in progress
HINT:  WAL control functions cannot be executed during recovery.
wal_e.main   ERROR    MSG: Could not stop hot backup
        STRUCTURED: time=2014-05-05T22:21:49.875087-00 pid=8763
```

I attempted the `--while-offline` flag, but that fails on the existence of a postmaster lock file, since it is, technically, not offline.

Any ideas, recommendations, hugs?

**Comment by jfrost** [comment]
The way to go might be to support something like [pg_espresso](https://github.com/2ndquadrant-it/pgespresso) with it's replacement start/stop backup functions.

The pgespresso_start_backup function returns the backup_label which we would then just need to stick into the archive.

**Comment by miketheman** [comment]
@jfrost I believe one of the problems of running pgespresso_start_backup on a non-writable standby is that the backup label initiation requires some sort of write call, which is denied on hot standby nodes.

**Comment by jfrost** [comment]
pgespresso is what [barman](http://docs.pgbarman.org/) uses to take base backups from the replica.

Check out the section of the docs labeled `Concurrent Backup and backup from a standby`

**Comment by miketheman** [comment]
@jfrost thanks - I must have overlooked that. I guess I didn't see the underlying api calls yet to get a label.

**Comment by rghose** [comment]
@jfrost Barman seems to do too much magic, I kind of would like it, if this was present as a part of wal-e.

**Comment by amitlan** [comment]
User-space concurrent (non-exclusive) backup API of 9.6 seems useful for this.

**Comment by fdr** [comment]
On Thu, May 19, 2016 at 1:45 AM Amit Langote <notifications@github.com>
wrote:

> User-space concurrent (non-exclusive) backup API of 9.6 seems useful for
> this.
>

Yeah. I've been waiting for something like that for a long time.

**Comment by Slach** [comment]
@fdr could you implement backup-push with hot_standby = on for postgresql 9.6 ?

**Comment by fdr** [comment]
On Mon, Jul 24, 2017 at 9:39 PM Eugene Klimov <notifications@github.com>
wrote:

> @fdr <https://github.com/fdr> could you implement backup-push with
> hot_standby = on for postgresql 9.6 ?
>

Wasn't planning on it myself...

**Comment by jacum** [comment]
Could this be a solution:
https://github.com/wal-e/wal-e/pull/407?

**Comment by jacum** [comment]
I wonder if any of maintainers can comment something on that. 
It may be a downright wrong approach altogether, this is also a valuable feedback I'd definitely appreciate.
