### ISSUE TITLE
Support Google Cloud Storage

### ISSUE THREAD

**Issue by paddycarver** [wal-e/wal-e#122]
Google has [their own](http://cloud.google.com/storage) cloud storage solution, and the use of Google Compute Engine + Google Cloud Storage is pretty equivalent to EC2 + S3, including the availability of "instance credentials".

While I, personally, wouldn't make the claim that Google's cloud solution is somehow inherently better, they made some free usage available to me, so I plan on running some open source applications there backed by Postgres. I'd love to be able to keep my WAL in the internal network and take advantage of the instance credentials that are already there.

As part of this effort, I've forked the repo and have been systematically walking through it, mirroring AWS/Swift/WABS files with new GCS files. I've almost finished building things out, but I thought I should open an issue and see if there are any objections to supporting this. I'm happy to do the work and contribute the patch upstream, but before I waste a bunch more time on it, is there any objection to merging such a pull request? It's not worth maintaining my own fork for, in my mind, so if it's not likely to be merged back in, I'll abandon it and store things in S3 or use GCS's S3 compatibility mode, which lacks some of the niceties.

**Comment by bastienlegras** [comment]
hello, any news on GCS integration ?

**Comment by fdr** [comment]
On Jan 23, 2015 8:30 AM, "bastienlegras" <notifications@github.com> wrote:
>
> hello, any news on GCS integration ?

Nobody has submitted a patch yet.

**Comment by lbosque** [comment]
Hi guys,

Any news about this?
Is there any ongoing branch with this feature? Is help needed?

**Comment by fdr** [comment]
On Wed, May 20, 2015 at 7:40 AM, Luis Bosque <notifications@github.com>
wrote:

> Hi guys,
>
> Any news about this?
> Is there any ongoing branch with this feature? Is help needed?
>
Not that I know of.  It's still awaiting someone to do it, or even see if
"S3_ENDPOINT" is good enough.

**Comment by dubanoze** [comment]
I try Simple migration from https://cloud.google.com/storage/docs/migrating.
Is work.

**Comment by RichardKnop** [comment]
@dubanoze How should the WALE_S3_ENPOINT look? I tried:

```
export WALE_S3_ENDPOINT=https+path://www.googleapis.com/download/storage/v1/b/
```

**Comment by dubanoze** [comment]
root@60b0d6d1c8eb:/etc/wal-e.d/env# cat WALE_S3_ENDPOINT 
http+path://storage.googleapis.com
root@60b0d6d1c8eb:/etc/wal-e.d/env#

**Comment by RichardKnop** [comment]
So I tried it like this:

```
export AWS_ACCESS_KEY_ID=my_key_id
export AWS_SECRET_ACCESS_KEY=my_secret_key
export WALE_S3_PREFIX=s3://richard-mcp-postgres-backup/wal-e
export WALE_S3_ENDPOINT=http+path://storage.googleapis.com
/usr/local/bin/wal-e --aws-access-key-id $AWS_ACCESS_KEY_ID backup-push /var/lib/postgresql/9.3/main/
```

But I am getting an error:

```
postgres@richard-tsuru-postgres:~$ /usr/local/bin/wal-e --aws-access-key-id $AWS_ACCESS_KEY_ID backup-push /var/lib/postgresql/9.3/main/
wal_e.operator.backup INFO     MSG: start upload postgres version metadata
        DETAIL: Uploading to s3://richard-mcp-postgres-backup/basebackups_005/base_00000001000000000000002D_00000040/extended_version.txt.
        STRUCTURED: time=2015-07-07T11:48:51.972975-00 pid=31340
wal_e.operator.backup WARNING  MSG: blocking on sending WAL segments
        DETAIL: The backup was not completed successfully, but we have to wait anyway.  See README: TODO about pg_cancel_backup
        STRUCTURED: time=2015-07-07T11:48:52.370380-00 pid=31340
```

Is there something wrong with the way I am trying to do this?

@dubanoze

**Comment by dubanoze** [comment]
You export WALE_S3_PREFIX=s3://richard-mcp-postgres-backup/wal-e

But upload to s3://richard-mcp-postgres-backup/basebackups_005/base_00000001000000000000002D_00000040/extended_version.txt.

s3://richard-mcp-postgres-backup not s3://richard-mcp-postgres-backup/wal-e


May be your exports not used ?
And you must use - The Interoperability API in Google cloud storage.

**Comment by russss** [comment]
We've managed to get this working mostly with Google Cloud Storage using the S3 compatibility layer, however `wal-e delete --confirm everything` fails with a HTTP 400 "Cannot create buckets using a POST" error.

Seems like a native storage backend for GCE may still be the way to go.

**Comment by fdr** [comment]
Native might be nice, but in the interest of brevity I'd like to think it can be constructed in a way to share a lot of code with S3, unless boto is no longer a preferred driver for GCE. This makes it unique from the copy-pasta-modify technique used with the two other storage backends to some decent effect.

**Comment by paddyforan** [comment]
Finally circling back around to being a high priority for me. I have the beginning of a patch worked up, but based on comments here, I think it may be better to go in a different direction.

It _looks_ like we could just use `boto` natively (i.e., still getting all the benefits of automatic credential detection within Google Compute Engine) if we use the [gcs-oauth2-boto-plugin](https://github.com/GoogleCloudPlatform/gcs-oauth2-boto-plugin) that the Google Cloud Platform team has created. Is there any reason we shouldn't go that route? Basically, is the added dependency a show-stopper, if it means we can continue using boto?

**Comment by fdr** [comment]
On Sun, Jul 19, 2015 at 12:31 AM Paddy <notifications@github.com> wrote:

> Finally circling back around to being a high priority for me. I have the
> beginning of a patch worked up, but based on comments here, I think it may
> be better to go in a different direction.
>
> It *looks* like we could just use boto natively (i.e., still getting all
> the benefits of automatic credential detection within Google Compute
> Engine) if we use the gcs-oauth2-boto-plugin
> <https://github.com/GoogleCloudPlatform/gcs-oauth2-boto-plugin> that the
> Google Cloud Platform team has created. Is there any reason we shouldn't go
> that route? Basically, is the added dependency a show-stopper, if it means
> we can continue using boto?
>
I'm okay going with whatever is idiomatic for modern use of Google Storage.
If that means a brand new backend, fine, but if means boto+epsilon, even
better. It's more important for me that the code be idiomatic to the
backend (so maintainers will touch it) than the shortest possible or with
maximum reuse.

One dependency seems like acceptable currency to get the feature.

**Comment by mattupstate** [comment]
I've been successfully interfacing with GCS with boto via `boto.connect_gs(access_key, secret_key)`, where if `access_key` and `secret_key` are `None`, credentials are retrieved from the local VM instance metadata service

**Comment by wint00** [comment]
There is a lot going on here. So, to get this all to work, you need the following? Or is there something else? Outside the container the ENV would be export of course.

ENV PG_DEPLOYMENT_TYPE=replicated
ENV PG_ROLE=master
ENV PG_PASSWORD=pguser
ENV PG_WAL_E_ENABLED=True
ENV PG_WAL_LEVEL=hot_standby
ENV WALE_S3_PREFIX=gs://gcs-scratchbucket/wint00
ENV AWS_ACCESS_KEY_ID=None
ENV AWS_SECRET_ACCESS_KEY=None
ENV WALE_S3_ENDPOINT=http+path://storage.googleapis.com

and edit my /etc/boto.cfg file to add:
connect_gs(access_key=None, secret_key=None)

**Comment by fdr** [comment]
I've actually been going over this patch (recently, sorry for the long delay). It's pretty large so it'll take me a little while, not least of which would be getting a GCE account and making a `blackbox.py` test. If would really help if you could make a `blackbox.py` test.

**Comment by codefx9** [comment]
@fdr, thanks for reviewing this patch. We would like to use this feature. Is there any update on the review process?

**Comment by fdr** [comment]
Did you see https://github.com/wal-e/wal-e/pull/211? I basically; need to go over it again and get it some testing.

**Comment by fdr** [comment]
(I mean, field tests. I wrote unit tests and blackbox tests as I saw fit already)

**Comment by jrysig** [comment]
What is current state of the GCS integration? Does current WAL-E release version work with GCS or should we rather wait for https://github.com/wal-e/wal-e/pull/359? Please advise...

**Comment by deverant** [comment]
It does work, although there are some issues with large datasets. Those issues seem to be fixed by the PR in question so I'll the merging it soon.

**Comment by deverant** [comment]
I am closing this issue since Google Cloud Storage is supported and has received plenty of hardening and battle testing over the months.
