### ISSUE TITLE
feature request: allow overridding all boto config settings from /etc/boto.cfg

### ISSUE THREAD

**Issue by carmstrong** [wal-e/wal-e#135]
This covers #134, #129, #131 

Basically, I'd like my settings in `/etc/boto.cfg` to override any best-guesses that WAL-e currently makes. Specifically, I am running Ceph locally with Ceph's object store gateway, which is S3 and Swift API-compatible. After lots of messing around with a simple boto script to create a bucket:

``` python
#!/usr/bin/env python
import boto
import sys
from boto.s3.connection import OrdinaryCallingFormat

conn = boto.connect_s3(port=8888,calling_format=OrdinaryCallingFormat())
bucket = sys.argv[1]

if not bucket in conn.get_all_buckets():
  conn.create_bucket(bucket)
```

and this `/etc/boto.cfg`:

```
[Boto]
is_secure = False

[s3]
host = deis-store-gateway
```

I can successfully create a bucket. However, WAL-e doesn't respect these settings - I seem to be unable to connect. I can force WAL-e to use `OrdinaryCallingFormat` by naming my bucket something funky so it doesn't pass [_is_mostly_subdomain_compatible](https://github.com/wal-e/wal-e/blob/ea31a3f0a69419e0627e2979aca7ecbb35114bf5/wal_e/blobstore/s3/calling_format.py#L54-L72), but it's still not connecting to the host I specified. And there seems to be no way to change the port.

Does refactoring WAL-e to perhaps merge its best-guess settings with those hardcoded in `/etc/boto.cfg`make sense? The operator should be able to override settings, as he/she arguably knows better than WAL-e exactly what's to be accomplished.

**Comment by decibel** [comment]
Just because boto is an abstraction why does that mean WAL-E should blitz it's configuration?

In particular, I'm trying to change where boto is getting it's certificates from and it's not working, presumably because of WAL-E over-riding the config. :(

**Comment by fdr** [comment]
On Thu, Nov 5, 2015 at 4:17 PM Jim Nasby <notifications@github.com> wrote:

> Just because boto is an abstraction why does that mean WAL-E should blitz
> it's configuration?
>
> In particular, I'm trying to change where boto is getting it's
> certificates from and it's not working, presumably because of WAL-E
> over-riding the config. :(
>

I don't blitz everything. I just take control of credentials and calling
formats. Your problem might be related, but if so, it's not clear how.

I have considered revising this approach, particularly if I switch to
boto3, but frankly, boto is bad at this stuff, and WAL-E predates the era
when drivers for a cloud service were particularly good or first party, so
it won't be happening anytime soon.
