### ISSUE TITLE
Problems with Frankfurt region / S3

### ISSUE THREAD

**Issue by hokkaido** [wal-e/wal-e#152]
I currently can't use WAL-E with S3 and a bucket located in Frankfurt:

`The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.`

I use a simple bucket prefix in the form of s3://mybucket/test/test. I think eu-central-1 requires Signature Version 4 Authentication unlike other regions. Strangely enough, another Bucket, also placed in the Frankfurt region, with the exact same AWS credentials and permissions, works without a hitch with WAL-E. I think it might be a problem on the end of S3.

**Comment by fdr** [comment]
I'm actually looking into this quite seriously. I have a prototype and am cleaning it up. It will be part of a v0.9 release

**Comment by danielmacho72** [comment]
Thanks. In the meantime (and for who may help) I'm using S3 bucket in Ireland (not having this problem)

**Comment by koen-serry** [comment]
I'm using the following in the eu-central-1 region without issue. I needed a recent boto though.

AWS_REGION -> eu-central-1
WALE_S3_PREFIX -> s3://s3-bucket/my-archives

**Comment by fdr** [comment]
Indeed I think this has been solved for some time. Thanks for bringing it to my attention to clean it up...

**Comment by Bryji** [comment]
I've just encountered this issue while using Spilo (from Zalando) in the UK region. Looks like Spilo installs from pip: https://github.com/zalando/spilo/blob/09b4cc3c18c0b1d8e666157171794a2a181cdc14/postgres-appliance/Dockerfile#L409

Could it be that the pip version doesn't have this fix?

This problem may be about to become much more visible:
> Revised Plan – Any new buckets created after June 24, 2020 will not support SigV2 signed requests, although existing buckets will continue to support SigV2 while we work with customers to move off this older request signing method.
https://aws.amazon.com/blogs/aws/amazon-s3-update-sigv2-deprecation-period-extended-modified/
