### ISSUE TITLE
Use multipart upload to avoid base backup socket errors

### ISSUE THREAD

**Issue by lrowe** [wal-e/wal-e#160]
I'm seeing errors uploading backups similar to https://groups.google.com/forum/#!topic/wal-e/KwbXdasIDUE when uploading from a local VM with slow networking.

Perhaps these problems could be managed better by using multipart uploading when the file size is over a threshold, so only failed parts need retrying. See: http://boto.readthedocs.org/en/latest/s3_tut.html#storing-large-data

The best upload/download performance I've seen is with the aws-cli utility which puts files to s3 using multiple parts in parallel using a threaded executor: https://github.com/aws/aws-cli/blob/master/awscli/customizations/s3/s3handler.py

**Comment by fdr** [comment]
The problem is multipart can leave behind chunks and is non-portable. What version of wal-e are you using? I found a different kind of problem that can yield the same issue.

**Comment by lrowe** [comment]
I'm on wal-e 0.6.6 at the moment. Do you have any pointers to the multipart leaving behind chunks problem?

It looks like each blobstore already has its own custom `uri_put_file` method. https://github.com/wal-e/wal-e/blob/master/wal_e/blobstore/s3/s3_util.py#L38

**Comment by fdr** [comment]
On Jan 14, 2015 8:10 PM, "Laurence Rowe" <notifications@github.com> wrote:
>
> I'm on wal-e 0.6.6 at the moment. Do you have any pointers to the
multipart leaving behind chunks problem?

In general, the way it works is one uploads chunks and then one finalizes
the upload. If one fails to do the latter, perhaps at some point WAL-E can
somehow decide at length that the multi-part is never going to finish and
clean up.

I'd advise trying an upgrade to the current "master".  I did some of these
optimizations to deal with some of the matters in small VMs and the effect
could be drastic and solve your problem.

**Comment by fdr** [comment]
So far, I have not seen a reason to get interested in multi-part upload when considering the alternative options and portability issues.
