### ISSUE TITLE
busybox lzop problem

### ISSUE THREAD

**Issue by aledbf** [wal-e/wal-e#165]
The `lzop` command in busybox doesn't support `--stdout` flag. Instead it uses `-c`
It could be possible to check the supported flags?

**Comment by fdr** [comment]
Is there a flag choice that works on all platforms?  "-c" is documented on my Ubuntu machine, for example.

**Comment by aledbf** [comment]
@fdr  from the ubuntu man page `--stdout` or `--to-stdout` are alias to `-c`
```
OPTIONS
       -c, --stdout, --to-stdout
           Write output on standard output. If there are several input files, the output consists of a sequence of independently (de)compressed members. To obtain better compression, concatenate all input files before compressing them.
```

**Comment by fdr** [comment]
perhaps submit a patch if `-c` is the only flag held in common on all known implementations.  Please add a comment as the rationale for the choice is obscure.

**Comment by aledbf** [comment]
@fdr done https://github.com/wal-e/wal-e/pull/171

**Comment by fdr** [comment]
Alright, it's been merged.

**Comment by aledbf** [comment]
@fdr thanks.
