### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by gigaroby** [wal-e/wal-e#167]
Hi, I'm trying to use wal-e to perform backups of a postgresql-9.3 machine with the following command:

```
AWS_ACCESS_KEY_ID="**************" AWS_SECRET_ACCESS_KEY="************" wal-e --s3-prefix=s3://bucket-in-eu-west-1 backup-push /pgsql/data/
```

After the successful compression of the wal segments I get this error:

```
wal_e.worker.upload INFO     MSG: Retrying send because of a socket error
        DETAIL: The socket error's message is '[Errno 104] Connection reset by peer'.  There have been 1 attempts to send the volume 0 so far.
        STRUCTURED: time=2015-02-25T14:28:49.081626-00 pid=16563
wal_e.worker.upload INFO     MSG: Retrying send because of a socket error
        DETAIL: The socket error's message is '[Errno 104] Connection reset by peer'.  There have been 1 attempts to send the volume 2 so far.
        STRUCTURED: time=2015-02-25T14:28:52.020640-00 pid=16563
wal_e.worker.upload INFO     MSG: Retrying send because of a socket error
        DETAIL: The socket error's message is '[Errno 104] Connection reset by peer'.  There have been 1 attempts to send the volume 1 so far.
        STRUCTURED: time=2015-02-25T14:29:13.155651-00 pid=16563
wal_e.worker.upload INFO     MSG: Retrying send because of a socket error
        DETAIL: The socket error's message is '[Errno 104] Connection reset by peer'.  There have been 1 attempts to send the volume 3 so far.
        STRUCTURED: time=2015-02-25T14:29:22.809143-00 pid=16563
wal_e.worker.upload INFO     MSG: Retrying send because of a socket error
        DETAIL: The socket error's message is '[Errno 104] Connection reset by peer'.  There have been 2 attempts to send the volume 0 so far.
        STRUCTURED: time=2015-02-25T14:29:25.700230-00 pid=16563
wal_e.worker.upload INFO     MSG: Retrying send because of a socket error
        DETAIL: The socket error's message is '[Errno 104] Connection reset by peer'.  There have been 2 attempts to send the volume 2 so far.
        STRUCTURED: time=2015-02-25T14:29:32.775549-00 pid=16563
wal_e.worker.upload INFO     MSG: Retrying send because of a socket error
        DETAIL: The socket error's message is '[Errno 104] Connection reset by peer'.  There have been 2 attempts to send the volume 1 so far.
        STRUCTURED: time=2015-02-25T14:30:13.549601-00 pid=16563
wal_e.worker.upload INFO     MSG: Retrying send because of a socket error
        DETAIL: The socket error's message is '[Errno 104] Connection reset by peer'.  There have been 3 attempts to send the volume 2 so far.
        STRUCTURED: time=2015-02-25T14:30:46.947130-00 pid=16563
wal_e.worker.upload INFO     MSG: Retrying send because of a socket error
        DETAIL: The socket error's message is '[Errno 104] Connection reset by peer'.  There have been 2 attempts to send the volume 3 so far.
        STRUCTURED: time=2015-02-25T14:30:53.544445-00 pid=16563
wal_e.worker.upload INFO     MSG: Retrying send because of a socket error
        DETAIL: The socket error's message is '[Errno 104] Connection reset by peer'.  There have been 3 attempts to send the volume 0 so far.
        STRUCTURED: time=2015-02-25T14:31:00.177826-00 pid=16563
```

This does not appear to be a problem with permissions because the file ```extended_version.txt``` is uploaded successfully.
This also happens when postgresql tries to archive the wal segments (so it's not an issue with the size of the chunk being uploaded).
The machine from which I'm trying to perform the upload is a c3.medium in the same region (eu-west-1).

I have already read the discussion on google groups but I have not found a definitive answer there (reducing the concurrency did not help).
Plase let me know if I can provide any more information to help debug this problem.

**Comment by Houdini** [comment]
Same here

**Comment by szymonpk** [comment]
Reconsider changing bucket to us. Worked for me.

**Comment by fdr** [comment]
Is this a new bucket?

**Comment by szymonpk** [comment]
Yup, today I've created few, eu-central doesn't work due to #152, eu-west doesn't work due to connections reset by peer. Us works like a charm.

**Comment by fdr** [comment]
I have noticed that DNS-addressed buckets can take some time to propagate.  I've seen similar defects with newly created buckets.

Also, I not sure if WAL-E's retries (really, Boto's) necessarily re-resolve in DNS.

In general, there is not much to be done about "Connection Reset by Peer", since it means whatever is on the other side is closing the connection.

In practice, it often boils down to either a credential failure or the the newly-created-bucket thing.

**Comment by danielmacho72** [comment]
I think this is related and has also to do with S3 having "connection reset by peer" problems

https://github.com/docker/distribution/issues/785

**Comment by danielmacho72** [comment]
For whoever is having same issue. I managed to make this work by (thanks to @DRazumovskiy, see https://github.com/boto/boto/issues/2207) 

- Using bucket in Ireland (to avoid V4 auth problem)
- Specifying WALE_S3_ENDPOINT=http+path://s3-eu-west-1.amazonaws.com:80 

Using this I do not get the reset-by-peer issue anymore

**Comment by fdr** [comment]
I am about to fix (actually, I have a patch and am trying it out) SigV4. But you realize that this ships whatever it is unencrypted, because it's `http+path` not `https+path`, right? This could be material if you aren't putting your instances in Ireland AWS too...

**Comment by asteinlein** [comment]
Just following up from the suggestion by @danielmacho72, using WALE_S3_ENDPOINT=https+path://s3-eu-west-1.amazonaws.com:443 also seems to work (I haven't gotten any connection reset by peers error using that so far), and is more secure.
