### ISSUE TITLE
Does wal-e require archive cleanup?

### ISSUE THREAD

**Issue by AKurilin** [wal-e/wal-e#170]
I've recently set up a hot standby postgres 9.3 server that uses wal-e to fetch archived WAL from s3. The instructions in the official docs state that you should be cleaning up after yourself after the archive chunk has been downloaded and imported: http://www.postgresql.org/docs/9.3/static/warm-standby.html#STANDBY-SERVER-SETUP

I wonder if the same is necessary with wal-e ? Specifically, do I want to use `archive_cleanup_command` for anything? Here's my current `recovery.conf`:

    standby_mode = 'on'
    primary_conninfo = 'host=192.168.1.1 port=5432 user=postgres password=foo
    restore_command = '/usr/bin/envdir /etc/wal-e.d/env /usr/local/bin/wal-e wal-fetch "%f" "%p"'
    # no clue what to configure the below to
    archive_cleanup_command = 'pg_archivecleanup /path/to/archive %r'

Does wal-e take care of this so I don't have to clean up anything through the command above?

**Comment by fdr** [comment]
It is typically not used, because it's basically designed to allow standby recovery exactly once, per the documentation you linked to:

```
If you're using a WAL archive, its size can be minimized using the archive_cleanup_command parameter to remove files that are no longer required by the standby server. The pg_archivecleanup utility is designed specifically to be used with archive_cleanup_command in typical single-standby configurations, see pg_archivecleanup. Note however, that if you're using the archive for backup purposes, you need to retain files needed to recover from at least the latest base backup, even if they're no longer needed by the standby.
```

In principle you can do whatever you want, but almost invariably people schedule a `wal-e delete` somehow.
