### ISSUE TITLE
"invalid syslog facility" warning printed when syslog is not enabled

### ISSUE THREAD

**Issue by slotrans** [wal-e/wal-e#173]
```
$ export AWS_ACCESS_KEY_ID=stuff
$ export AWS_SECRET_ACCESS_KEY=things
$ export WALE_S3_PREFIX=s3://places/
$ export WALE_LOG_DESTINATION=stderr
$ wal-e version
wal_e.log_help WARNING  MSG: invalid syslog facility level specified
        STRUCTURED: time=2015-03-31T17:27:41.652670-00 pid=23374
0.8.0
```

Looking at `log_help.py`, I see this:
```python
    if not valid_facility:
        WalELogger(__name__).warning(
            msg='invalid syslog facility level specified')
```

Which is not within the `if 'syslog' in log_destinations:` conditional, so this message will always be printed when not using syslog, which doesn't make sense to me.

**Comment by fdr** [comment]
That seems like an oversight.  Can you submit a patch?

**Comment by fdr** [comment]
This was committed in d461ea2b6ef96194b6fd741b5a7ec52dbedb2b08

**Comment by martonsz** [comment]
Nice to see this bug being fixed. But when will it be released as a new version? I am using pip to install wal-e and the latest version there is 0.8.0 from March 25 2015

**Comment by fdr** [comment]
On Fri, Jun 5, 2015 at 2:33 AM Márton Szücs <notifications@github.com>
wrote:

> Nice to see this bug being fixed. But when will it be released as a new
> version? I am using pip to install wal-e and the latest version there is
> 0.8.0 from March 25 2015
>
I bet I can release this today. There's a somewhat touchy fix in
https://github.com/wal-e/wal-e/commit/d84ff02a0cbc17d42b3f075c6f3d978223abf799,
but if someone saw fit to complain about wanting some of the new patches,
it's probably worth the risk.
