### ISSUE TITLE
backup-fetch hangs on OS X (again)

### ISSUE THREAD

**Issue by bjs987** [wal-e/wal-e#174]
I see that back in Jan/Feb of 2014 (issue #90) that changes were proposed to address a hang that prevents backups from being downloaded on Mac (OS X).  

I am running wal-e 0.8.0 and this issue is still happening for me all the time.

The backup-fetch command hangs indefinitely on OS X.  This is occurring while trying to download from S3.

Hoping for any advice.

**Comment by bjs987** [comment]
Never mind, it appears that this error was caused by not having permissions to write to $PGDATA.  Not sure why it hanged instead of just bailing out though.  Will close issue, although it might make be worth investigating the hang when an unexpected error occurs.

**Comment by snocorp** [comment]
I just wanted to say thanks for this issue. I was stumped for a while and was thrown off by the other issue with the same name that looked solved until I saw this one.
