### ISSUE TITLE
Consider replacing gevent with eventlet

### ISSUE THREAD

**Issue by evansd** [wal-e/wal-e#178]
As reported in #176, gevent does not work with Python 2.7.9 (now the default shipped with Ubuntu Vivid) and appears to be unmaintained. The last release of gevent was 2014-04-30 and the last commit to the repo was  2014-12-13. The [relevant bug](https://github.com/gevent/gevent/issues/477) was filed on 2014-09-12 and still hasn't been addressed.

By contrast, eventlet fixed this issue in 0.16, released on 2014-12-30 and continues to be in active development.

If you think this is a viable option I'd be happy to try to create a PR for it. The two libs are fairly similar so I'm hoping it won't be too much work.

**Comment by fdr** [comment]
Yeah, I'm not terribly enthused by the state of that bug.

Very interesting.  It also supports Python3? Do you know any catches? I was toying with going straight to threading and dropping any eventing library, but this is a pretty big change...but I don't see it is being intractable.  Unfortunately I think my use of gevent in WAL-E's early days was a design error.  Do you have any interest in that alternate option?

I suggest you try doing this on a prototype-quality basis, so I can take some measurements of performance and you can see how hard it is. If it seems promising then I can pitch in if necessary.  I'd like to go to Python3 and that appears to be supported by eventlet.

**Comment by evansd** [comment]
I don't know of any catches. The author of gevent explains why he originally forked eventlet [here](http://blog.gevent.org/2010/02/27/why-gevent/), but I think most of his original concerns have been addressed in eventlet now, and I don't know if they'd be relevant to WAL-E in any case.

I would definitely prefer a solution using just threads though. Anything that reduces WAL-E's dependencies, particularly non-pure-Python ones would be a win from my point of view.

I'll have a go at a prototype eventlet patch as soon as I get a chance, though that may not be for a week or so.

**Comment by fdr** [comment]
On May 15, 2015 10:18 AM, "David Evans" <notifications@github.com> wrote:
>
> I don't know of any catches. The author of gevent explains why he
originally forked eventlet here, but I think most of his original concerns
have been addressed in eventlet now, and I don't know if they'd be relevant
to WAL-E in any case.
>
> I would definitely prefer a solution using just threads though. Anything
that reduces WAL-E's dependencies, particularly non-pure-Python ones would
be a win from my point of view.
>
> I'll have a go at a prototype eventlet patch as soon as I get a chance,
though that may not be for a week or so.

Good luck, I'll be looking forward to it, though I recognize how hard it is
to find the time.

**Comment by evansd** [comment]
It looks like the gevent bug is fixed in v1.0.2: https://github.com/gevent/gevent/blob/1.0.2/changelog.rst#release-102-may-23-2015

I still feel that eventlet might be a more reliable dependency (plus it gives the option of Python 3 support) so I'd still like to do some exploratory work to see how much effort the switch would be -- just a question of finding the time!

**Comment by evansd** [comment]
Gevent [now supports](https://github.com/gevent/gevent/blob/master/changelog.rst#11a1-jun-29-2015) Python 3. It's probably not worth spending the time looking at eventlet.
