### ISSUE TITLE
Multithread backup fetch

### ISSUE THREAD

**Issue by lbosque** [wal-e/wal-e#179]
Hi guys,

Is there any plan to support downloading the main backup file (with fetch) with multithread?
More or less the same thing about downloading a file with axel (http://axel.alioth.debian.org/) instead of using wget.

Thanks

**Comment by fdr** [comment]
I'd like that, but it doesn't seem worth the effort, and no one has volunteered...at least, not to me right now.

If I had to pick a problem to solve bottlenecks, it'd be supporting multiple CPUs.
