### ISSUE TITLE
FreeBSD: hangs, but backup restores succesfully

### ISSUE THREAD

**Issue by wunki** [wal-e/wal-e#180]
Pushing wal-files and base-backups works just fine. However, when I do a `backup-fetch` it fetches all the segments, but when it's done, it just hangs. No network or CPU activity. 

Strange thing is, after closing the program with CTRL-C I could start the database and it was restored like it should be.

Any idea why it should hang or how I could debug this?

Thanks!

With the following version:
- wal-e == 0.8.0
- six == 1.9.0
- gevent == 1.0.2

**Comment by fdr** [comment]
Consider installing a signal handler to dump stack traces from SIGUSR1, e.g. http://stackoverflow.com/questions/132058/showing-the-stack-trace-from-a-running-python-application
