### ISSUE TITLE
runtime error when starting wal-e due to new pbr library

### ISSUE THREAD

**Issue by mboersma** [wal-e/wal-e#181]
The [`pbr`](https://pypi.python.org/pypi/pbr/1.0.1) library was updated recently, and in our CI system this seems to cause a runtime error starting `wal-e`. From our [functional tests](https://ci.deis.io/job/test-coreos-alpha/187/console):
```python
database: performing an initial backup...
Traceback (most recent call last):
  File "/usr/bin/wal-e", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3074, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3060, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3087, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 647, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 660, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 838, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pbr 1.0.1 (/usr/lib/python2.7/site-packages), Requirement.parse('pbr!=0.7,<1.0,>=0.6'), set(['oslo.config', 'oslo.i18n', 'stevedore', 'oslo.serialization', 'oslo.utils']))
```

At least that is my assessment of what is probably happening--I haven't been able to reproduce this locally yet. If so, pinning `pbr==0.11.0` might fix it, because that's what I see in the most recent test runs where this was passing. 

Here is where the requirement is introduced:
```
Collecting pbr<2.0,>=0.11 (from python-keystoneclient>=0.4.2->wal-e==0.8.0)
  Downloading pbr-1.0.1-py2.py3-none-any.whl (83kB)
```

**Comment by jberkus** [comment]
Reverting pbr to 0.11.0 didn't fix this for me:

postgres:~$ envdir /etc/wal-e.d/env wal-e backup-push
Traceback (most recent call last):
  File "/usr/local/bin/wal-e", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests>=2.5.2

**Comment by mboersma** [comment]
It's kind of a blunt workaround, but it did work for us in the PR linked to above. This is building wal-e inside a Docker container using Alpine Linux and Python 2.7.9.

Maybe one of `oslo.config` or `stevedore` will update, since they seem to be constraining the version to between 0.6 and 1.0 (minus version 0.7). Somehow those constraints are ignored until runtime, and it's only `python-keystoneclient` that's in requirements.txt, and it's perfectly happy downloading `pbr` 1.0.1...

**Comment by jberkus** [comment]
Well, here's my pip freeze:

apt-xapian-index==0.45
azure==0.11.0
Babel==1.3
boto==2.38.0
chardet==2.0.1
colorama==0.2.5
configobj==4.7.2
envdir==0.7
futures==3.0.2
gevent==1.0.2
greenlet==0.4.7
html5lib==0.999
iso8601==0.1.10
Landscape-Client==14.12
msgpack-python==0.4.6
netaddr==0.7.14
netifaces==0.10.4
oslo.config==1.11.0
oslo.i18n==1.6.0
oslo.serialization==1.5.0
oslo.utils==1.5.0
PAM==0.4.2
pbr==0.11.0
prettytable==0.7.2
pycurl==7.19.3
pyOpenSSL==0.13
pyserial==2.6
python-apt===0.9.3.5ubuntu1
python-dateutil==2.4.2
python-debian===0.1.21-nmu2ubuntu2
python-keystoneclient==1.5.0
python-swiftclient==2.4.0
pytz==2015.4
requests==2.2.1
simplejson==3.7.2
six==1.5.2
ssh-import-id==3.21
stevedore==1.4.0
Twisted-Core==13.2.0
urllib3==1.7.1
virtualenv==1.11.4
wal-e==0.8.0
wheel==0.24.0
zope.interface==4.0.5

**Comment by jberkus** [comment]
Oh, I see the problem.

Apparently the wal-e pip package does not, in fact, install the requirements.  A bunch of those are too old.  Fixing, but shouldn't the pip package take care of this?

**Comment by mboersma** [comment]
So for the `pbr` problem, it appears this specific problem has been [fixed in `oslo.config`](https://github.com/openstack/oslo.config/commit/cc9940f91ebf91c9b827462441d0ea9b8b3b0efd). I'll make a PR to have `wal-e` require `oslo.config` 1.12.0, which is a better fix than pinning `pbr`.

**Comment by fdr** [comment]
I don't understand the current state of this bug. Is it broken as of now?  A fresh virtualenv worked for me.

The problem with throwing in some requires in a point release is it can break upgraders if there was some past version that worked fine.

**Comment by jberkus** [comment]
I've resolved my version of the problem by adding extra requirements, per the other issue I filed.

**Comment by mboersma** [comment]
Pinning `oslo-config` to a version at or after 1.12.0 removes its incorrect requirement for `pbr`, which fixes the issue we saw. It would be preferable to have `python-keystoneclient` pin this in its requirements, but currently it only asks for `oslo-config>=1.11.0`. See also deis/deis#3786.

I didn't address the need to include `requests` or `six` in requirements in #183 because those weren't relevant to the problem we saw running `wal-e`. @fdr I'm not sure why it isn't reproducible for you in a fresh virtualenv. The conflicting requirements for `pbr` are there however, until `oslo-config` was fixed recently.

**Comment by fdr** [comment]
I'm not going to include transitive dependencies to work around a bug I can't reproduce and could break existing users.  Here's a transcript of things working fine:

```
$ virtualenv --no-site-packages /tmp/test; source /tmp/test/bin/activate
Running virtualenv with interpreter /usr/bin/python2
New python executable in /tmp/test/bin/python2
Also creating executable in /tmp/test/bin/python
Installing setuptools, pip...done.
(test)fdr@sputnik:~/codes/shogun$ pip install wal-e
[lots of output, mostly from gevent]
Successfully installed wal-e gevent boto azure python-swiftclient python-keystoneclient greenlet python-dateutil pyopenssl futures six requests simplejson oslo.serialization stevedore oslo.i18n pbr netaddr PrettyTable iso8601 Babel oslo.utils oslo.config cryptography msgpack-python pytz netifaces debtcollector idna pyasn1 enum34 ipaddress cffi wrapt pycparser
Cleaning up...
(test)fdr@sputnik:~/codes/shogun$ wal-e
usage: wal-e [-h] [-k AWS_ACCESS_KEY_ID | --aws-instance-profile]
             [-a WABS_ACCOUNT_NAME] [--s3-prefix S3_PREFIX]
             [--wabs-prefix WABS_PREFIX] [--gpg-key-id GPG_KEY_ID] [--terse]
             {version,backup-fetch,backup-list,backup-push,wal-push,wal-fetch,wal-prefetch,delete}
             ...
wal-e: error: too few arguments
```

**Comment by jberkus** [comment]
what versions of six and requests do you have installed?

**Comment by fdr** [comment]
```
(test)$ pip freeze
Babel==1.3
argparse==1.2.1
azure==0.11.0
boto==2.38.0
cffi==1.1.2
cryptography==0.9.1
debtcollector==0.5.0
enum34==1.0.4
futures==3.0.2
gevent==1.0.2
greenlet==0.4.7
idna==2.0
ipaddress==1.0.7
iso8601==0.1.10
msgpack-python==0.4.6
netaddr==0.7.14
netifaces==0.10.4
oslo.config==1.12.1
oslo.i18n==1.7.0
oslo.serialization==1.6.0
oslo.utils==1.6.0
pbr==1.1.1
prettytable==0.7.2
pyOpenSSL==0.15.1
pyasn1==0.1.7
pycparser==2.13
python-dateutil==2.4.2
python-keystoneclient==1.6.0
python-swiftclient==2.4.0
pytz==2015.4
requests==2.7.0
simplejson==3.7.3
six==1.9.0
stevedore==1.5.0
wal-e==0.8.1
wrapt==1.10.4
wsgiref==0.1.2
```

**Comment by jberkus** [comment]
Yeah, so you already have modern versions of Six and Requests installed, which is why you didn't notice them as requirements.  Try installing on a RHEL5 container, and you'll see the problem.

**Comment by fdr** [comment]
Is this possibly Python 2.6 related, if we're talking something so old?

**Comment by fdr** [comment]
Are you installing via pip into a --no-site-packages virtualenv?  I can't figure why a fresh install would Do The Wrong Thing as-is.  Or is this some conflict with libraries installed on that platform?

**Comment by jberkus** [comment]
It is python 2.6-related.  That is, the target machine was upgraded to python 2.7.  But in that case, apparently it doesn't upgrade six and requests.

**Comment by fdr** [comment]
Are you using Openstack, per chance, or is it just an unwelcome hanger-on here? Because that's where the bulk of problems in dependencies come from.

**Comment by mboersma** [comment]
The `pbr` issue is still there; you only have to read the requirements.txt files from python-keystoneclient and earlier versions of oslo.config to see that they specify mutually incompatible requirements for `pbr`. This issue did happen with `pip install` as I cited and linked to above, and it stopped our CI system dead for a few days.

It isn't happening to you because a fresh install today finds newer versions of `oslo.config` that realized they had no dependency on `pbr`, and removed it:
```console
$ pip install wal-e
Collecting oslo.config>=1.11.0 (from python-keystoneclient>=0.4.2->wal-e==0.8.0)
  Downloading oslo.config-1.12.1-py2.py3-none-any.whl (68kB)
    100% |████████████████████████████████| 69kB 825kB/s 
```

This will probably work, but it's still potentially dangerous that python-keystoneclient only requires `oslo.config>=1.11.0`. If it actually installs 1.11.0, things will break. I suppose this isn't `wal-e`'s issue specifically, we were just hoping for an upstream fix rather than hacking around it ourselves, as we have done.

I'll leave this issue open as it is apparently focusing on an unrelated problem now.

**Comment by jberkus** [comment]
Nope.  Standard RHEL system.

**Comment by fdr** [comment]
Are either of you using OpenStack?

The OpenStack client dependencies have caused a towering amount of complaint (which is to say, several, vs the others, which are none). I'm thinking that I should implement optionality of OpenStack and this will ablate most issues.

I was already careful to only dynamically load the libraries I need for a backend, so adding some error messages might handle the rest.

**Comment by mboersma** [comment]
> Are either of you using OpenStack?

Not us.

**Comment by jberkus** [comment]
I'm not encountering this anymore.  The underlying pip libraries seem to have straightened out.

Close?

**Comment by mboersma** [comment]
Things have been sorted out in the `pip` ecosystem, and AFAICT this isn't relevant now. I'll close it.
