### ISSUE TITLE
six, requests need to be added to requirements

### ISSUE THREAD

**Issue by jberkus** [wal-e/wal-e#182]
wal-e requires requests >= 2.5.2 and six >= 1.9.0.  However, these aren't listed in the requirements or included in the pip dependencies.  

More info in bug #181

**Comment by fdr** [comment]
It looks like that bug is the one that has a resolution. I guess I'll close this one.

**Comment by jberkus** [comment]
Are these requirements now pulled in by the oslo.config requirement?  If so, then this one is closed; otherwise, it's not.
