### ISSUE TITLE
PostgreSQL 8.4 doesn't support 'wal_level' setting

### ISSUE THREAD

**Issue by boncey** [wal-e/wal-e#198]
I've just finished setting up wal-e for a postgreSQL 8.4.22 instance (on Ubuntu Linux).

When I restarted my database after adding the suggested config values I got this error.

    FATAL:  unrecognized configuration parameter "wal_level"

I commented out that line and restarted my database - it is now running fine and writing files to my S3 bucket.
However, I'm not sure if it's actually doing the right thing.
How can I tell if it's working correctly?

The [docs for 9.0](http://www.postgresql.org/docs/9.0/static/runtime-config-wal.html) say:

    The default value is minimal...
    But minimal WAL does not contain enough information to reconstruct the data from a base backup and the WAL logs, so either archive or hot_standby level must be used to enable WAL archiving (archive_mode) and streaming replication.

I can't seem to find out what the default behaviour is on 8.4.

**Comment by jordan-thoms** [comment]
I think from reading http://www.postgresql.org/docs/8.4/static/continuous-archiving.html that turning archive_mode on would change the wal level:

When archive_mode is off some SQL commands are optimized to avoid WAL logging, as described in Section 14.4.7. If archiving were turned on during execution of one of these statements, WAL would not contain enough information for archive recovery. (Crash recovery is unaffected.) For this reason, archive_mode can only be changed at server start. However, archive_command can be changed with a configuration file reload. If you wish to temporarily stop archiving, one way to do it is to set archive_command to the empty string (''). This will cause WAL files to accumulate in pg_xlog/ until a working archive_command is re-established.


Although It'd probably be recommended to upgrade to a supported version of Postgres.

**Comment by boncey** [comment]
I thought 8.4 was supported by `wal-e`.
It's implied in the README.

```
psql (>= 8.4)
```

**Comment by fdr** [comment]
In the very, very early days of WAL-E, it backed up and restored 8.4 databases, no doubt. I hypothesize that back then, the `wal_level` setting didn't exist: either you were doing log-shipping (which is what WAL-E is: a log shipper), or you weren't, and if you were log shipping the WAL format grew whatever overhead it needed to to be useful

If in doubt, try a restore, and/or carefully read the sections involving wal-shipping in the 8.4 manual.
