### ISSUE TITLE
Wal-e and docker recommendation

### ISSUE THREAD

**Issue by gregbkr** [wal-e/wal-e#200]
Good afternoon,

I hope I am in the right place to ask more a question than an issue.

I am implementing Wal-e on a test infrastructure and it works great so far! Thank you for all your efforts!

1. Is there any official docker image you guys recommends? (I am using abevoelker/postgres which include Postgres+Wal-e). 

2. Is it possible to use Wal-e to backup a remote database? Until now I manage only to backup the local Postgres in the same container. I couldn't find the right command to use a Wal-e container (ex: jonathantron/wal-e) linked to a db container (postgres:9.3) in order to backup the db file to s3.

Thank you for any feedback, and very good week everyone!

Regards,
Greg.

**Comment by zjeraar** [comment]
Wal-e in my dockerfile:

```
RUN \
  curl -O https://bootstrap.pypa.io/get-pip.py && \
  python get-pip.py && \
  rm get-pip.py && \
  pip install gevent==1.0.2 && \
  pip install boto==2.38.0 && \
  pip install wal-e==0.8.1
```

**Comment by gregbkr** [comment]
Good evening Zjeraar,

Do you manage to run this Wale outside the db container?
We managed to install Wale in the dockerfile of our postgres db, but last week, the db container failed. Still investigation why... Will be great if I could run Wale ouside the db container and not touch that db... 

Thank you and good start of week! ;-)
Greg.

**Comment by zjeraar** [comment]
Well, the way we use it is by the archive command in the postgresql configuration file(which performs a wal-push command), so the postgresql container needs to be able to use wal-e. I think that makes it difficult to do in another container.

If you only use the backup-push command, you can just share the postgresql data container with a seperate wal-e container and run wal-e seperately. Never tried, but I see no reason why that shouldn't work.

**Comment by gregbkr** [comment]
Thanks for the tip, didn't think of that. I will try if the db fails again because of a backup. Cheers! ;-)

**Comment by fdr** [comment]
Thanks for answering this issue. re-open it if anything gets hairy.

**Comment by davidham** [comment]
@zjeraar I got postgres and WAL-E working by  creating my own Dockerfile based on postgres. It runs continuous backups with the archive_command set to wal-push, and that part runs fine. However, I also want to run base backups 1-2x a day. I had been doing this with a cron task that ran `backup-push` through  `docker exec`. However, I am now set up on Amazon ECS, and I can't do `docker exec` because there's no way for the script to know the name of the postgres container.

Is there a way to run `backup-push` from a different container, and by linking to my running postgres container?

**Comment by fdr** [comment]
On Mon, Jun 20, 2016 at 2:44 PM David Ham <notifications@github.com> wrote:

> @zjeraar <https://github.com/zjeraar> I got postgres and WAL-E working by
> creating my own Dockerfile based on postgres. It runs continuous backups
> with the archive_command set to wal-push, and that part runs fine. However,
> I also want to run base backups 1-2x a day. I had been doing this with a
> cron task that ran backup-push through docker exec. However, I am now set
> up on Amazon ECS, and I can't do docker exec because there's no way for
> the script to know the name of the postgres container.
>
> Is there a way to run backup-push from a different container, and by
> linking to my running postgres container?
>

You might be able to set something up by using PGHOST as a TCP address
rather than a unix socket address (the default) and sharing volumes, while
ensuring to carefully map file permissions. But this all seems rather
complicated relative to running WAL-E in the same container.

**Comment by zjeraar** [comment]
@davidham, in my postgres container I run everything with a bash script. I have a function there that is something like this:

```
periodically_backup () {
  while true; do
    sleep 45

    local current_time=$(date +"%H:%M")
    if [[ "$current_time" == "$BACKUP_EXECUTION_TIME" ]]; then
      local wale_s3_prefix=$(create_wale_prefix)
      wal-e --s3-prefix="$wale_s3_prefix" backup-push "$DATA_DIRECTORY"
      wal-e --s3-prefix="$wale_s3_prefix" delete --confirm retain 30
    fi
  done
}
```

and then in the script
```
periodically_backup &
```

**Comment by davidham** [comment]
@fdr agreed, totally. @zjeraar I love this! And you could manage this all with the stock postgres image, with environment vars and the script in docker-initdb.d. Thanks so much for your response.

**Comment by davidham** [comment]
@zjeraar Can you describe a little more about how you have this set up? In my container I have a setup-wal-e.sh script, which sets `archive_mode` and `archive_command`, and kicks off a version of your `periodically_backup` in the background. I copy this into `docker-entrypoint-initdb.d`, and it runs great when I am creating a new database; however, when I run it with a volume containing my existing database, I can't tell how to run it without it exiting when I close the shell. Do I run `periodically_backup &` in the script and then run `./setup-wal-e.sh &` in a docker terminal (opened with `docker exec -it mycontainer bash`? Thanks for any advice you can offer!

**Comment by zjeraar** [comment]
@davidham I don't use the official postgres image (I think you're referring to). I have my own image with one bash script which kicks of the periodically_backup in the background and after that starts the db (also in the background). All this is done with the initial docker run command.

Something like:
```
echo "start periodically backup at $BACKUP_EXECUTION_TIME""h..."
periodically_backup &

echo "starting postgresql..."
/usr/lib/postgresql/9.4/bin/postgres -c config_file=/etc/postgresql/postgresql.conf &

# wait for the pid of this file to end
wait $!
```

**Comment by davidham** [comment]
@zjeraar this is very helpful, thank you.
