### ISSUE TITLE
Experiencing high CPU usage and low performance

### ISSUE THREAD

**Issue by halvorgb** [wal-e/wal-e#205]
I've started using WAL-E and I'm experiencing what I'd call slow recovery speeds. I'm running on an AWS t2.medium instance restoring wal segments from S3, it has managed to restore 396 segments in about 4 hours. Or to contextualize, ~5 hours of wal segments restored in ~4 hours.

I'm seeing lots of forking of wal-e processes, I'm seeing wal-e trying to fetch the same segments multiple times.

Python version: 2.7.6
wal-e version: 0.8.1

These are (from what I recall) the relevant postgres config parameters, I'm quite certain that these aren't wrong as I've already had some help looking them over.
postgresql.conf values:

```
wal_buffers=16MB
checkpoint_segments = 64
checkpoint_completion_target= 0.9

archive_mode = on
archive_command = '/usr/local/bin/wal-e --aws-instance-profile  wal-push %p'
archive_timeout = 60
```

recovery.conf values:

```
standby_mode = on
primary_conninfo = 'host=$MASTER_HOST port=5432 application_name=$INSTANCE_ID user=replication password=$REPLICATION_PASSWORD'
restore_command = '/usr/local/bin/wal-e --aws-instance-profile wal-fetch \"%f\" \"%p\"'
recovery_target_timeline = 'latest'
```

I get this error:

```
Oct 28 13:05:55 a459853e1dc7 wal_e.blobstore.s3.s3_util INFO     MSG: completed download and decompression
Oct 28 13:05:55 a459853e1dc7 DETAIL: Downloaded and decompressed "s3://postgres-wal-staging/wal_005/0000001900000CC7000000E4.lzo" to "/var/lib/postgresql/9.3/main/pg_xlog/.wal-e/prefetch/running/0000001900000CC7000000E4/tmpxvzztg"
Oct 28 13:05:55 a459853e1dc7 STRUCTURED: time=2015-10-28T13:05:55.967814-00 pid=13492
Oct 28 13:05:56 a459853e1dc7 wal_e.operator.backup INFO     MSG: complete wal restore
Oct 28 13:05:56 a459853e1dc7 STRUCTURED: time=2015-10-28T13:05:55.971474-00 pid=13492 action=wal-prefetch key=s3://postgres-wal-staging/wal_005/0000001900000CC7000000E4.lzo prefix= seg=0000001900000CC7000000E4 state=complete
Oct 28 13:05:56 a459853e1dc7 wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
Oct 28 13:05:56 a459853e1dc7 DETAIL: Traceback (most recent call last):
Oct 28 13:05:56 a459853e1dc7 File "/usr/local/lib/python2.7/dist-packages/wal_e/cmd.py", line 582, in main
Oct 28 13:05:56 a459853e1dc7 backup_cxt.wal_prefetch(args.BASE_DIRECTORY, args.SEGMENT)
Oct 28 13:05:56 a459853e1dc7 File "/usr/local/lib/python2.7/dist-packages/wal_e/operator/backup.py", line 404, in wal_prefetch
Oct 28 13:05:56 a459853e1dc7 return ret
Oct 28 13:05:56 a459853e1dc7 File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/prefetch.py", line 59, in __exit__
Oct 28 13:05:56 a459853e1dc7 shutil.rmtree(self.prefetch_dir.seg_dir(self.segment))
Oct 28 13:05:56 a459853e1dc7 File "/usr/lib/python2.7/shutil.py", line 239, in rmtree
Oct 28 13:05:56 a459853e1dc7 onerror(os.listdir, path, sys.exc_info())
Oct 28 13:05:56 a459853e1dc7 File "/usr/lib/python2.7/shutil.py", line 237, in rmtree
Oct 28 13:05:56 a459853e1dc7 names = os.listdir(path)
Oct 28 13:05:56 a459853e1dc7 OSError: [Errno 2] No such file or directory: '/var/lib/postgresql/9.3/main/pg_xlog/.wal-e/prefetch/running/0000001900000CC7000000E4'
Oct 28 13:05:56 a459853e1dc7 
Oct 28 13:05:56 a459853e1dc7 STRUCTURED: time=2015-10-28T13:05:56.264574-00 pid=13492
```

I get it a lot:

```
root@a459853e1dc7:/# cat /var/log/syslog | grep -i "OSError" | wc -l           
1731
```

Loads of processes

```
root@a459853e1dc7:/# ps -ef | grep wal-e | wc -l 
50
```

More begins than completes:

```
root@a459853e1dc7:/# cat /var/log/syslog | grep  "begin wal restore" | wc -l
7194
root@a459853e1dc7:/# cat /var/log/syslog | grep  "complete wal restore" | wc -l
3628
```

Multiple commands referencing the same segment:

```
root@a459853e1dc7:/# cat /var/log/syslog | grep  "s3://postgres-wal-staging/wal_005/0000001A00000CC7000000E0.lzo" | wc -l
19
```

Full syslog: https://gist.github.com/anonymous/c7f43d2a59c92f3d2070
`ps -ef | grep wal-e` output:  https://gist.github.com/anonymous/4284485f3af161c8ac44

**Comment by fdr** [comment]
Hmm. Try turning off prefetching. I think something may be up with file system permissions that prevent wal-e being able to track what's in progress very well.

**Comment by halvorgb** [comment]
Thanks for the reply, this is a bit outdated, but for any future googlers:

Like this[0] post we ran wal-e and postgres in a docker container[1] while we experienced these issues. We've since reverted back to installing postgres (and wal-e) the old fashioned way and experience none of these problems. 

[0]:http://comments.gmane.org/gmane.comp.db.postgresql.wal-e/490
[1]:A slightly modified version of https://github.com/abevoelker/docker-postgres

**Comment by fdr** [comment]
I can't quite see why that would matter, except for possible file permission issues and a bug in wal-e that doesn't quite cope with it very well.  One area I've had issues with in Docker containers generally is careful management of /etc/passwd and uids and moving files around.

Perhaps the way you were using Docker data volumes or overlay file systems could contribute too.  Naively, based on my understanding of cgroups, this should not matter: Heroku has been running wal-e inside cgroups for years and years.
