### ISSUE TITLE
backup-fetch should end with some useful information

### ISSUE THREAD

**Issue by chrisduong** [wal-e/wal-e#212]
Hi,

I think it is very nice and also less confused if you let the user know the backup-fetch job has done successfully with some useful information ( like finish time, how long it takes, etc,...). 

In my personal experience, I had been running a long backup-fetch job, I have to go out for awhile, and when I come back I only see that some partition been downloaded from S3, and no more. I thought it failed so I had to run it again.

Thanks.

**Comment by fdr** [comment]
That sounds pretty good. Want to write it in?

**Comment by chrisduong** [comment]
I don't have much experience in Python (I'm mostly Rubiest) , besides I'm quite busy during this quarter. :(
