### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by WillPlatnick** [wal-e/wal-e#213]
Hey all,
Not to be a pain, but are you guys planning on keeping WAL-E up? I noticed no issues have been talked about in over a month. If it's been abandoned, would you be willing to have someone else take over maintenance?

**Comment by bshi** [comment]
Daniel seems to be maintaining a healthy clip of activity for a storage infrastructure project.  Is there a specific issue you need addressed?

https://github.com/wal-e/wal-e/pulls?q=is%3Apr+sort%3Aupdated-desc

**Comment by WillPlatnick** [comment]
Thanks for getting back to me. Yes, this issue is causing me a lot of issues:

https://github.com/wal-e/wal-e/issues/208

Looking to get some kind of feedback on the proper fix. Willing to submit the PR myself, but don't want to do something the "wrong" way and wanted to gather some opinions before I got started.

**Comment by bshi** [comment]
Lets move the discussion to #208 then.
