### ISSUE TITLE
B2

### ISSUE THREAD

**Issue by mathiasrw** [wal-e/wal-e#222]
Any plans to support [B2 storage from backbalze](https://www.backblaze.com/b2/cloud-storage.html)?

**Comment by fdr** [comment]
I don't have any such plans, and so far I've been stuck maintaining (with some trepidation) backends that I do not use (and find bugs in), which is every one except AWS, so I'm not inclined to accept a patch either unless I think the maintainer is going to stick with finding bugs, solving them, and dealing with change for a few years.

**Comment by mathiasrw** [comment]
Makes good sense
