### ISSUE TITLE
using wal-e restore command disables streaming replication

### ISSUE THREAD

**Issue by pdeva** [wal-e/wal-e#224]
Using postgres 9.5, ubuntu 14.04 and wal-e 0.8.1

If i put both `primary_conninfo` and `restore_command` properties in my `recovery.conf` file, it seems postgres ignore the `primary_conninfo` since it no longer does streaming replication and waits for wal-e archives.

Is  this expected?

Also i notice that wal-e fetch runs every single seconds and tries to fetch the next wal archive. While it does manage to fetch the next archive at the end of every minute when it is eventually generated on the master, the postgres log gets full of error msgs.

Is this expected too?

**Comment by fdr** [comment]
Postgres will switch between the `restore_command` and `primary_conninfo` to fetch WAL. I've noticed it's quite terse on the standby (recovering) side about problems connecting: try checking the primary.

Every time once of these methods encounters an error, it'll attempt a switch back to the other.
