### ISSUE TITLE
Can WAL-E send WAL and basebackups to two independent places?

### ISSUE THREAD

**Issue by greaber** [wal-e/wal-e#239]
The title says it all.  I would like to backup to my cloud provider and also to a site across the Internet.  The thinking is that the cloud provider would be for "normal" backup protection, and the site across the Internet would provide protection against a catastrophic security breach at the cloud provider.  Can WAL-E handle this?

One issue I encountered when thinking about how to do this manually is what exit status to use if one backup succeeds and the other fails.  The best option would be to report failure, but then it would be necessary to keep track of the fact that one backup succeeded and not keep trying to redo that one.

**Comment by fdr** [comment]
Not right now, I'm afraid. It's be a pretty substantial feature. Double-archiving does have some appeal, though.
