### ISSUE TITLE
Ubuntu 12.04.5 LTS debtcollector install error

### ISSUE THREAD

**Issue by qguan-aa** [wal-e/wal-e#241]
sudo pip install wal-e
....

Downloading/unpacking debtcollector>=1.2.0 (from python-keystoneclient>=0.4.2->wal-e)
  Downloading debtcollector-1.3.0.tar.gz
  Running setup.py egg_info for package debtcollector
    
    Installed /home/qguan/build/debtcollector/pbr-1.9.1-py2.7.egg
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/home/qguan/build/debtcollector/pbr-1.9.1-py2.7.egg/pbr/core.py", line 111, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/home/qguan/build/debtcollector/pbr-1.9.1-py2.7.egg/pbr/util.py", line 248, in cfg_to_args
        kwargs = setup_cfg_to_setup_kwargs(config, script_args)
      File "/home/qguan/build/debtcollector/pbr-1.9.1-py2.7.egg/pbr/util.py", line 431, in setup_cfg_to_setup_kwargs
        if pkg_resources.evaluate_marker('(%s)' % env_marker):
    AttributeError: 'module' object has no attribute 'evaluate_marker'
    error in setup command: Error parsing /home/qguan/build/debtcollector/setup.cfg: AttributeError: 'module' object has no attribute 'evaluate_marker'
    Complete output from command python setup.py egg_info:
    

Installed /home/qguan/build/debtcollector/pbr-1.9.1-py2.7.egg

**Comment by qguan-aa** [comment]
I know this package is related to some openstack client package, considering it is quite complicated to involve too much clients to install, is it possible to install wal-e just enable s3 client?

**Comment by indispeq** [comment]
Same error here on debian wheezy. Any way to get around it?

**Comment by rodo** [comment]
@indispeq thanks for this hint !

**Comment by fdr** [comment]
w.r.t. dependencies, yeah, see https://github.com/wal-e/wal-e/issues/246#issuecomment-232442952
