### ISSUE TITLE
Initial recovery of standby never succeeds when using --terse: FATAL:  the database system is starting up

### ISSUE THREAD

**Issue by earsdown** [wal-e/wal-e#245]
Initial recovery of standby fails when using --terse. To reproduce this annoying bug, simply follow the "Fetching a backup" instructions at https://gist.github.com/elithrar/8682235, except add the `--terse` option to the `restore_command` in `recovery.conf`.

You will find that postgresql won't complete its startup procedure, and your logs will fill up an endless loop of this message:

```
< 2016-04-27 07:58:19.302 UTC >FATAL:  the database system is starting up
< 2016-04-27 07:58:20.304 UTC >FATAL:  the database system is starting up
< 2016-04-27 07:58:21.306 UTC >FATAL:  the database system is starting up
< 2016-04-27 07:58:22.308 UTC >FATAL:  the database system is starting up
< 2016-04-27 07:58:23.310 UTC >FATAL:  the database system is starting up
< 2016-04-27 07:58:24.319 UTC >FATAL:  the database system is starting up
< 2016-04-27 07:58:25.321 UTC >FATAL:  the database system is starting up
< 2016-04-27 07:58:26.323 UTC >FATAL:  the database system is starting up
< 2016-04-27 07:58:27.325 UTC >FATAL:  the database system is starting up
< 2016-04-27 07:58:28.326 UTC >FATAL:  the database system is starting up
< 2016-04-27 07:58:29.337 UTC >FATAL:  the database system is starting up
```

The workaround is to simply remove the `--terse` option, restart postgresql, then put the `--terse` option back in. This would be fine if we were manually managing a small number of standbys, but trying to do this via puppet at scale is a nightmare.

**Comment by fdr** [comment]
Wait, what? Are you sure about this? Because unless `--terse` is breaking the exit code, it should not have much effect. These logs are not emitted by WAL-E, but rather triggered by any client that attempts to connect while the database is becoming consistent.

**Comment by earsdown** [comment]
@fdr  well... this bug plagued me for several days, and the only fix I could find was to remove the `--terse` option. I'm running postgresql 9.4 (pgdg) on CentOS 7, which should be irrelevant, but if you aren't able to reproduce this bug on Ubuntu then it might have something to do with it.

**Comment by fdr** [comment]
That's very strange. I wonder if `--terse` causing a crash. Can you echo what exit codes wal-e is generating?

**Comment by earsdown** [comment]
How can I get the exit code? In this case, wal-e is being called by postgresql via recovery.conf's restore_command ...

**Comment by fdr** [comment]
I'd write a small program to echo the exit code and also return it to
postgres (think 'tee' but with exit codes)

Alternatively, instrument your copy of wal-e.

**Comment by earsdown** [comment]
So like a wrapper? Like this?

```bash
#!/bin/bash
wal-e "$@"
echo "WRAPPER: wal-e exit code was $?"
```

**Comment by earsdown** [comment]
Ha! @fdr , you're a genius. It shouldn't be a surprise but it turns out the issue had nothing to do with wal-e after all. My full restore_command was as follows:

```bash
restore_command =  '. /etc/bashrc ; AWS_REGION=ap-southeast-2 wal-e --terse --s3-prefix=s3://mybucket --aws-instance-profile wal-fetch "%f" "%p" 2>&1 | egrep -v "not a lzop file"'
```

What I hadn't realised was that egrep returns a non-zero status if wal-e doesn't produce the string "not a lzop file" ... which it won't do when --terse is turned on, obviously.

The solution was a slightly less brain-dead restore_command:
```bash
  restore_command = '. /etc/bashrc ; o="`AWS_REGION=ap-southeast-2 wal-e --terse --s3-prefix=s3://mybucket --aws-instance-profile wal-fetch "%f" "%p" 2>&1`" ; r=$? ; echo "$o" | egrep -v "not a lzop file" ; exit $r'
```

Thanks for pointing me in the right direction, much appreciated.
