### ISSUE TITLE
Backup-fetch does not recreate pg_hba.conf or postgresql.conf?

### ISSUE THREAD

**Issue by davidham** [wal-e/wal-e#249]
Hi,

This is more of a question than an issue, but here goes:

I am running WAL-E in a Docker container built on postgres:9.4. It's awesome and only just last week saved me during a deploy issue. During my restore sequence (which I got from this [very helpful gist](https://gist.github.com/elithrar/8682235), one of the first steps is to delete my $PGDATA directory, since backup-fetch recreates it. However, the pg_hba.conf and postgresql.conf files, which live there by default, do not get recreated. Do most people keep those configs in a different place? Are there any others that should also be kept outside of $PGDATA?

Thanks for this great tool!

**Comment by rodo** [comment]
I always store theses files under `/etc` there are not data, it's not a job for wal-e to restore configuration options.

**Comment by davidham** [comment]
You just keep these in /etc/postgres? Any others?

**Comment by rodo** [comment]
Yes, to be exact one dir per cluster, for example with 3 clusters on one of my host :

* /etc/postgresql/9.5/main/
* /etc/postgresql/9.6/main/
* /etc/postgresql/9.6/citus/

**Comment by davidham** [comment]
Cool, thank you for your reply, I'll update my setup this way.

**Comment by davidham** [comment]
Hi, I'm sorry to bother you again, but how do I tell postgres to look in a different location for those files? I'm using the postgres:9.4 image in Docker if it makes a difference. Thanks!
