### ISSUE TITLE
Restore backups in batches?

### ISSUE THREAD

**Issue by davidham** [wal-e/wal-e#250]
My backup restore is filling up my disks too fast (also posted as an issue on DBA StackExchange [here](http://dba.stackexchange.com/questions/139291/restoring-postgres-backup-with-wal-e-fills-up-disk). Is there a way to do a full restore in batches, or else is there a way to keep a restore from filling the disk? My actual data doesn't take that much space, but all the segments and logging files are maxing out my disks, both locally and at Amazon. Help! :)

**Comment by rodo** [comment]
It seems you find a solution, may we close this issue ?

**Comment by davidham** [comment]
Yes, sorry about that!
