### ISSUE TITLE
Doesn't work with Python 2 anymore?

### ISSUE THREAD

**Issue by mattklein** [wal-e/wal-e#263]
Is it intended that the master branch doesn't build for Python 2 anymore? Is there a branch that supports Python 2? 1.0, 0.9, 0.8, 0.7 don't seem to either. At some point (a few months ago?) the version in PIP did, but I don't know when that stopped being the case.

**Comment by fdr** [comment]
v0.9 is still Python 2. It hasn't changed at all.

v1.0 and master are a Python 3.4+ project only, now.
