### ISSUE TITLE
Orphan wal-prefetch processes hog all system resources

### ISSUE THREAD

**Issue by deverant** [wal-e/wal-e#264]
Not sure if this might happen with other backends, but at least happens with GCS:

While running the current master branch with python 3.4 I'm left with an ever growing number of wal-prefetch processes that never die. This will finally cause the OOM killer to kick in.

All of the zombies look like this:
```
postgres 124520  Sl   05:38   0:00 python bin/wal-e wal-prefetch /var/lib/postgresql/9.5/main/pg_xlog 000000010000096E0000007F
postgres 124561  SL   05:38   0:00  \_ gpg -d -q --batch
postgres 124562  Z    05:38   0:00  \_ [lzop] <defunct>
```

From the logs it looks like a wal-fetch is called for the same segment shortly after the wal-prefetch starts. There is nothing in the logs that would indicate what went wrong with the zombie wal-prefetch process.

**Comment by deverant** [comment]
Ok, in my case the problem ended up being with gpg. 

```
$ gpg --version
gpg (GnuPG) 1.4.16
```

When executed in the forked and daemonized wal-prefetch process it throws this line first into stdin, which of course makes the input to lzop no longer a proper lzo file:

```
gpg: WARNING: standard error reopened
```

I have no idea why this happens now and not with the old 0.9 branch and python 2.7. Anyways the issue can be fixed by just making sure we have an `stderr` available in the daemonized process. The question is where do you think it should be put?

Options:
 * Handle `stderr` in the PipelineCommand. This gets a bit tricky since normally when wal-e is called we want to stderr to work normally.
 * Set `stderr` to `/dev/null` in DaemonContext, or something that will log all the errors?

My first vote is to just `/dev/null` since we don't really do anything with the stderr nowadays anyway.

Another issue sort of related to this is that wal-e currently doesn't seem to handle the case where the subprocess dies and the streams don't get properly closed.

**Comment by fdr** [comment]
It might be due to a change in `subprocess`, or perhaps the daemonization is not working quite as well as it once did. Yet, it's the same module as used in the Python 2.7 releases.

If you kill `gpg`s in this predicament, does the problem clear up? I'm wondering if prefetch is getting stuck on `wait`ing for the process.

**Comment by deverant** [comment]
I did `gdb` into the process, and also did some additional logging. It never returns from the `write_and_return_error` and more specifically `copyfileobj` is stuck waiting for the buffer to clear so it can move more bytes over? 

I guess it might be that lzop doesn't close the buffer correctly or `pipebuf` hides it somehow?

**Comment by fdr** [comment]
I think it's okay to direct stderr to `/dev/null`, as with `prefetch` it has nowhere super useful to go.

**Comment by deverant** [comment]
Agreed. I also think it's the simplest fix that has the least chance of causing other problems. Next week I'll figure out if I can somehow test this and then merge the fix to master.

**Comment by deverant** [comment]
I have a fix in deverant/wal-e@ceddf699fb7c4ef5141617e451f9e064c0b3e781. Do you want to test it out before I merge it? I don't currently have a chance to test any other backends except GCS.

Also the wal-prefetching with forking is hard to test. Got weird errors with pytest and DaemonContext fighting for stdout and capturing..

**Comment by fdr** [comment]
yeah, I had to remove it from the tests because it was interacting badly with pytest. Regretfully a full-blown integration test is necessary.

**Comment by fdr** [comment]
Why don't you give your change a try. I think it'll fix/break all backends together.
