### ISSUE TITLE
Logging message doesn't show on exit code 2.

### ISSUE THREAD

**Issue by monaka** [wal-e/wal-e#268]
I got troubles like deis/postgres#127 in the recovery mode.

I inspect code and I got "exit code 2 is from sys.exit(2) in cmd.py".
But I can't figure out a reason why I couldn't find log messages generated by logging.critical().
Logging messages may be buffered and lost? It should be flushed?

**Comment by monaka** [comment]
I added more than 10 logger.critical() before sys.exit(2). Log messages (10 or more) are shown.

I read code around logging. But I looks there have no flushing code in logger.critlcal().
So I think WAL-E exits with system code 2 before the message by logger.clitical() was called.
(Please notice me if I have mistaken as I'm not a Python hacker.)

**Comment by fdr** [comment]
Have you checked syslog? I thought that might be synchronous, but I'm not entirely sure.

**Comment by monaka** [comment]
I'm using wal-e in Docker. So I don't have syslogd...
I read logging modules deeper. I've not use debugger yet. But indeed it looks be flushed in StreamHandler.emit().

Could you keep this issue open for a few weeks? I'm going to continue to inspect this.

**Comment by fdr** [comment]
Sure. Thanks for looking into it.

**Comment by monaka** [comment]
Still I'm busy and I can't spend enough time for this issue.
I close it for now. I'll try to inspect later. I wish I could send a result in the near future.
