### ISSUE TITLE
Make deletion success or failure more apparent with S3

### ISSUE THREAD

**Issue by af6140** [wal-e/wal-e#271]
When there is no deletion right, command appears succcessful but actually did nothing and no error message.

**Comment by fdr** [comment]
Yeah. That's unfortunate. I would accept a patch that does something more useful with the error returns, if any, from the Amazon bulk-delete API, or even a phrasing change.

**Comment by secwall** [comment]
Hello. Should something like [this](https://github.com/secwall/wal-e/commit/9a7a69b12d219062f12fea89b7d2804cad84776b) fix this issue? Boto's bucket delete_keys returns `MultiDeleteResult` object with `errors` attribute (which is a list of unsuccessfully deleted objects).

**Comment by fdr** [comment]
On Sat, Feb 18, 2017 at 4:19 AM secwall <notifications@github.com> wrote:

> Hello. Should something like this
> <https://github.com/secwall/wal-e/commit/9a7a69b12d219062f12fea89b7d2804cad84776b>
> fix this issue? Boto's bucket delete_keys returns MultiDeleteResult
> object with errors attribute (which is a list of unsuccessfully deleted
> objects).
>
That looks right to me. Want to give it a try and make sure it does what
you want? Listing all the keys is probably overkill. Perhaps the first and
last key are enough.

**Comment by secwall** [comment]
I've tested with read-only user.
Environment setup:
1) Ubuntu Xenial
2) PostgreSQL 9.6
3) wal-e with [this patch](https://github.com/secwall/wal-e/commit/e034abbb5d4f5c14e7237af1b7940e1b6aecd59d)
4) Archived 5 wals with s3-full-access user
5) Run `/etc/wal-e.d/env_ro wal-e delete --confirm everything` with read-only user
Error log looks like this:
```
wal_e.retries WARNING  MSG: retrying after encountering exception
        DETAIL: Exception information dump:
        Traceback (most recent call last):
          File "/usr/local/lib/python3.5/dist-packages/wal_e/retries.py", line 62, in shim
            return f(*args, **kwargs)
          File "/usr/local/lib/python3.5/dist-packages/wal_e/worker/s3/s3_deleter.py", line 34, in _delete_batch
            len(result.errors))))
        wal_e.exception.UserException: ERROR: MSG: Some keys were not deleted
        DETAIL: Failed keys: first <Error: backup-test/wal_005/000000010000000000000002.lzo(AccessDenied)>, last <Error: backup-test/wal_005/000000010000000000000005.lzo(AccessDenied)>, 5 total
        STRUCTURED: time=2017-02-20T00:15:32.791514-00 pid=11278

        HINT: A better error message should be written to handle this exception.  Please report this output and, if possible, the situation under which it arises.
        STRUCTURED: time=2017-02-20T00:15:32.791659-00 pid=11278
```

**Comment by fdr** [comment]
Yeah. I think we could use a bit nicer error handling to avoid the information dumps, but that's not intrinsically related I don't think. Submit a PR?
