### ISSUE TITLE
Incorrect value for `Content-Encoding` header passed

### ISSUE THREAD

**Issue by david-dever-23-box** [wal-e/wal-e#272]
https://github.com/wal-e/wal-e/blob/master/wal_e/operator/backup.py#L243

`content_encoding` should be `identity` or removed altogether; value shown is a MIME type: `application/json`, not an encoding type. See https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.5

**Comment by fdr** [comment]
Can you submit a patch?

**Comment by fdr** [comment]
Oops, just saw your pr.

**Comment by fdr** [comment]
Closed as redundant, per #273
