### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by Tecktron** [wal-e/wal-e#274]
On Debian with python3, running using command:
`/usr/local/bin/wal-e`

with or without any params:
`/usr/bin/envdir /etc/wal-e.d/env /usr/local/bin/wal-e backup-push /storage/postgresql/data`

I'm getting this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/wal-e", line 7, in <module>
    from wal_e.cmd import main
  File "/usr/local/lib/python3.4/dist-packages/wal_e/cmd.py", line 528
    print pkgutil.get_data('wal_e', 'VERSION').strip()
```

Any ideas?

**Comment by fdr** [comment]
This looks like a Python2/v0.9.0 or before version of WAL-E combined with a new python.

The equivalent source code in 1.0 looks like:

```python
    if subcommand == 'version':
        import pkgutil

        print(pkgutil.get_data('wal_e', 'VERSION').decode('ascii').strip())
        sys.exit(0)
```

You can cooroborate this finding by looking at the `VERSION` file directly.

How did you install wal-e? You may need to add the `--pre` flag to your pip invocation.

**Comment by Tecktron** [comment]
Thanks for the info. Yeah, I installed it through `pip` I'll check out the `VERSION` file as suggested  and let you know what I find. If I need to,  I'll try and reinstall with the `--pre` flag see if that fixes it also.

**Comment by Tecktron** [comment]
The version was 0.9.2.
I ran `pip install wal-e --pre --upgrade` but now am getting this error:
```
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-push".
        STRUCTURED: time=2016-08-26T00:45:54.295177-00 pid=20140
wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
        DETAIL: Traceback (most recent call last):
          File "/usr/local/lib/python3.4/dist-packages/wal_e/cmd.py", line 565, in main
            backup_cxt = configure_backup_cxt(args)
          File "/usr/local/lib/python3.4/dist-packages/wal_e/cmd.py", line 466, in configure_backup_cxt
            creds = s3_explicit_creds(args)
          File "/usr/local/lib/python3.4/dist-packages/wal_e/cmd.py", line 401, in s3_explicit_creds
            from wal_e.blobstore import s3
          File "/usr/local/lib/python3.4/dist-packages/wal_e/blobstore/s3/__init__.py", line 10, in <module>
            from wal_e.blobstore.s3.s3_credentials import Credentials
          File "/usr/local/lib/python3.4/dist-packages/wal_e/blobstore/s3/s3_credentials.py", line 1, in <module>
            from boto import provider
        ImportError: cannot import name 'provider'
```

**Comment by Tecktron** [comment]
It seems some things were either incompatible or not installed correctly.
I ran these series of commands to get everything back up and running:
```
$ sudo pip freeze > installed.txt

$ sudo pip uninstall -y -r installed.txt

$ rm -rm ~/.cached/pip

$ sudo pip install wal-e --pre --no-cache

$ sudo pip install boto --no-cache
```

And now everything works!

Thanks for the help.

**Comment by fdr** [comment]
I was going to ask what version of boto was involved, with regard to the
import error, but I'm glad things worked out.
