### ISSUE TITLE
TypeError with Python 3.4 / Azure storage

### ISSUE THREAD

**Issue by ppetrid** [wal-e/wal-e#277]
Hello, trying to perform a `backup-push` with python 3.4 and using the azure storage I get the following error:

```
The exception type is <class 'TypeError'> and its value is Unicode-objects must be encoded before hashing

wal_e/blobstore/wabs/wabs_util.py", line 89, in upload_chunk
            check_sum = base64.b64encode(md5(chunk).digest()).decode('utf-8')

```

I tried wal-e 1.0.0b1 and 1.0.0a2 and both result in the same error.

**Comment by monaka** [comment]
Line 89 is patched by me. It works fine on my environment (Python3.5).
But I see there should be re-patched.

**Comment by monaka** [comment]
I expected that the type of `chunk` is bytes.
But in @ppetrid 's environment, it looks Unicode strings is passed to `chunk` .
We can regenerate similar error like this.

```
$ python3
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from hashlib import md5
>>> md5('foo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Unicode-objects must be encoded before hashing
>>> md5(b'foo')
<md5 HASH object @ 0x7f9b396ca260>
>>> 
```

But I can't imagine why Unicode object is passed.
The file pointer is generated in worker_util.py/do_lzop_put(). It is opend with the binary options.
So results of `read()` should be binaries, not Unicode.

**Comment by monaka** [comment]
@ppetrid , could you show more details about your environment? OS, distro., and so on.

**Comment by ppetrid** [comment]
Hello, I'm on Ubuntu 14.04.5 x86_64 (4.2.0-42-generic). Python version is 3.4.3. The official lzop package (1.03-3) is installed. If you're using docker, the ubuntu:14.04 image should reproduce it. I could also attach a dockerfile if that can help.

**Comment by monaka** [comment]
Thanks, @ppetrid.
I'm also using WAL-E in Docker container.
I'll try to reproduce.

**Comment by monaka** [comment]
Python3.4.3 works with expected behavior.
So the point may be Azure libs...

```
Python 3.4.3 (default, Oct 14 2015, 20:28:29)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from hashlib import md5
>>> md5('foo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Unicode-objects must be encoded before hashing
>>> md5(b'foo')
<md5 HASH object @ 0x7fb2f68885d0>
>>>
```

**Comment by fdr** [comment]
@ppetrid can you relate to us what version of the Azure client libraries you are using?

**Comment by ppetrid** [comment]
Hello, sorry for the late reaction.
`pip3 freeze` gives the following output:

```
azure==1.0.3
azure-common==1.1.4
azure-mgmt==0.20.2
azure-mgmt-common==0.20.0
azure-mgmt-compute==0.20.1
azure-mgmt-network==0.20.1
azure-mgmt-nspkg==1.0.0
azure-mgmt-resource==0.20.1
azure-mgmt-storage==0.20.0
azure-nspkg==1.0.0
azure-servicebus==0.20.1
azure-servicemanagement-legacy==0.20.2
azure-storage==0.20.3
chardet==2.2.1
colorama==0.2.5
gevent==1.1.2
greenlet==0.4.10
html5lib==0.999
python-dateutil==2.5.3
requests==2.2.1
six==1.5.2
urllib3==1.7.1
wal-e==1.0.0b1
wheel==0.24.0
```

I also attach a dockerfile that reproduces my environment. You can build the image with

`docker build --build-arg WABS_ACCESS_KEY="key" --build-arg WABS_ACCOUNT_NAME="account" --build-arg WALE_WABS_PREFIX="prefix" -f wal-e.txt -t wale:latest .`

When running the container with `docker run -ti wale` you enter bash. Just start postgres and attempt to backup, you should get the error.

[wal-e.txt](https://github.com/wal-e/wal-e/files/491095/wal-e.txt)

**Comment by perfectayush** [comment]
@monaka I am facing the same issue. I did some debugging. The reason Unicode strings is being passed to chunk is because, the first file it tries to upload is extended_version.txt, not binary blobs. The contents of this file is passed to uri_put_file as StringIO
https://github.com/wal-e/wal-e/blob/master/wal_e/operator/backup.py#L485-L487

`        uri_put_file(self.creds,
                     extended_version_url, StringIO(version),
                     content_type='text/plain')`

Since python3.4 cannot md5hash string, it's resulting in the error

**Comment by fdr** [comment]
On Tue, Oct 18, 2016 at 10:53 AM Ayush Goyal <notifications@github.com>
wrote:

> @monaka <https://github.com/monaka> I am facing the same issue. I did
> some debugging. The reason Unicode strings is being passed to chunk is
> because, the first file it tries to upload is extended_version.txt, not
> binary blobs. The contents of this file is passed to uri_put_file as
> StringIO
>
> https://github.com/wal-e/wal-e/blob/master/wal_e/operator/backup.py#L485-L487
>
> uri_put_file(self.creds,
> extended_version_url, StringIO(version),
> content_type='text/plain')
>
> Since python3.4 cannot md5hash string, it's resulting in the error
>
Good catch. Would you be so kind to submit a patch to encode the string?

**Comment by fdr** [comment]
@ppetrid I see you also did some Azure work in your branch. Anything you want to submit upstream for release?

**Comment by ppetrid** [comment]
@fdr My branch handles a separate issue with date/time returned by Azure and the LATEST keyword. I'll do some further testing against the latest `master` and open a new issue / PR if needed.

**Comment by monaka** [comment]
@perfectayush Thank you for your help.
