### ISSUE TITLE
CentOS 

### ISSUE THREAD

**Issue by Behner** [wal-e/wal-e#279]
Using wal-e 1.0.0b1, virutalenv with python 3.4 on CentOS 6.6. The `psql` command can be run no problem from the same command line. Any idea what I am missing or what I broke? This is my first attempt at installing this on CentOS 6.6.

`wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-push".
        STRUCTURED: time=2016-09-16T18:04:05.913767-00 pid=3124
psql: fe_sendauth: no password supplied
wal_e.main   ERROR    MSG: could not run one or more external programs WAL-E depends upon
        DETAIL: Could not get a connection to the database: note that superuser access
        is required
        Could not run the following programs, are they installed? psql
        STRUCTURED: time=2016-09-16T18:04:05.968915-00 pid=3124`

**Comment by Behner** [comment]
Needed to update access for the postgres user in pg_hba.conf. Fixed. Thanks.

**Comment by fdr** [comment]
Thanks for writing in. Your writing maybe useful for a future searcher, someday.
