### ISSUE TITLE
looking in wrong place for a file.. bug? ..  OSError: [Errno 2] No such file or directory: '/var/lib/postgresql/9.5/archive_status

### ISSUE THREAD

**Issue by preperat** [wal-e/wal-e#281]
thanks

**Comment by fdr** [comment]
Do you have wal-e in a wrapper script that changes the directory? WAL-E has expectations about its current working directory being one Postgres uses by default.

**Comment by fdr** [comment]
Closing on account of inactivity, reopen if you have more information.
