### ISSUE TITLE
Confused by disk space usage

### ISSUE THREAD

**Issue by boncey** [wal-e/wal-e#283]
I'm confused by the amount of disk space that my wal-e backups are taking up (and the associated AWS bill).

The total size of all my databases is a smidgen over 3GB.
Yet after running `wal-e` on an empty bucket for 12 days the total disk usage of that folder is`161GB`.

I run a full `backup-push` every week.
Also, I run a weekly job to delete all but the last five backups.

    /usr/local/bin/wal-e --terse delete --confirm retain 5

A few weeks back my S3 bucket had grown to half a terrabyte.
I ran the command to delete everything but after it had completed I still had a folder with `345GB` of data.
I cleaned that up by hand to start again from scratch.

When I now run the command to show backup size I see that I have three backups each around `4GB` in size.
Yet the total usage is `161GB` and rising.

Here are the relevant settings from my `postgresql.conf`.
```
wal_buffers = 16MB
wal_level = archive
archive_mode = on
archive_command = 'wal-e --terse wal-push %p'
archive_timeout = 60
```

Is all this normal (and if so, why) or am I doing something wrong?
Thanks, Darren.

**Comment by deverant** [comment]
Apart from the backups you do with `backup-push` you are also uploading every WAL (Write-ahead log) file to S3 (that is what the archive_command does). These files contain basically every modification to your database and allow doing point-in-time-recovery of the database.

So my first guess would be that you have a lot of write traffic in the database so you end up uploading a lot of WAL files into S3. What `delete` will do for you is delete WAL files older than any of the full backups left in storage.

**Comment by boncey** [comment]
Hello, thanks for replying.
What you say makes sense and my database is indeed write-heavy.

So do you know if there is anything I can do to reduce disk space?
As far as I can see it will just keep on growing.

**Comment by fdr** [comment]
Have you tried looking at `wal-e backup-list`, to make sure only five backups are retained? You might want to remove `--terse` to better see what's going on.

If that seems to be working properly, I'd list files in the WAL directory (`wal_005`) to see if there are not files significantly older than your oldest backup.

Finally, check your measurements. 160GiB of logs is more than I'd expect for such a small database.

If none of these things seem awry, then everything is probably in working order. If that storage is a problem for you, you may need to find out how to avoid logging so many data changes and coping with the reduced durability of those data changes.

**Comment by boncey** [comment]
Thanks for getting back to me.

I've had a think about it and have decided to turn off continuous archiving and just run a daily `backup-push` from cron.

If I do that then my storage costs should drop significantly.
I am happy to live with my database being up to 24 hours out of date.

My `postgresql.conf` now looks like this:
```
wal_level = archive
#archive_mode = on
#archive_command = 'wal-e --terse wal-push %p'
archive_timeout = 60
```

However, when I run a `backup-push` now I see this message at the end.
```
NOTICE:  WAL archiving is not enabled; you must ensure that all required WAL segments are copied through other means to complete the backup
```

Is that telling me that I am doing something wrong or is it safe to ignore?

Thanks, Darren.

**Comment by fdr** [comment]
On Sun, Oct 23, 2016 at 1:56 PM Darren Greaves <notifications@github.com>
wrote:

> Thanks for getting back to me.
>
> I've had a think about it and have decided to turn off continuous
> archiving and just run a daily backup-push from cron.
>
> If I do that then my storage costs should drop significantly.
> I am happy to live with my database being up to 24 hours out of date.
>
> My postgresql.conf now looks like this:
>
> wal_level = archive
> #archive_mode = on
> #archive_command = 'wal-e --terse wal-push %p'
> archive_timeout = 60
>
> However, when I run a backup-push now I see this message at the end.
>
> NOTICE:  WAL archiving is not enabled; you must ensure that all required WAL segments are copied through other means to complete the backup
>
> Is that telling me that I am doing something wrong or is it safe to ignore?
>

You need at least the WAL over the duration of the backup to recover the
database successfully. The two must be combined to make a complete base
backup.

**Comment by boncey** [comment]
OK, I understand, thanks.

I found [this blog post](https://edwardsamuel.wordpress.com/2016/05/24/set-up-scheduled-postgresql-backup-to-aws-s3-using-wal-e/) today that suggests configuring S3 to automatically delete files older than a set number of days.

I'm going to try that and see if it reduces disk space (and ultimately my AWS bill).

**Comment by fdr** [comment]
You can do that, yet it would not be different than triggering deletion via
WAL-E with a similar time criteria.

**Comment by boncey** [comment]
In theory yes, but as I mentioned above I still had 345GB of data left after deleting all backups.
So for me anyway, it's worth trying.

I'll report back in a few weeks if it made any difference or not.

Thanks again for all your help with this.

**Comment by boncey** [comment]
It's been a month since I set my S3 bucket to expire old data.
The size of the bucket is now 101.84GB.

So clearly doing it that way has made a difference (just deleting old backups using `/usr/local/bin/wal-e --terse delete --confirm retain 5` left the disk usage around 300GB after a month).
