### ISSUE TITLE
Does not exclude pg_replslot

### ISSUE THREAD

**Issue by mhagander** [wal-e/wal-e#296]
Base backups taken do not exclude the `pg_replslot` directory as they should. See 25.3.3.3 at https://www.postgresql.org/docs/9.6/static/continuous-archiving.html.

This can cause active replication slots to appear on the restored box, blocking xlog rotation.

**Comment by fdr** [comment]
Well that's not good.

**Comment by jkatz** [comment]
The workaround we are using is to clear all replication slots on load.

We are in a Python 2 environment still so if this patch can be backported to the 0.9.x series as well that would be awesome as we are unable to go to Python 3 in the near future.

**Comment by fdr** [comment]
On Mon, Nov 21, 2016 at 4:42 PM Jonathan S. Katz <notifications@github.com>
wrote:

> The workaround we are using is to clear all replication slots on load.
>
> We are in a Python 2 environment still so if this patch can be backported
> to the 0.9.x series as well that would be awesome as we are unable to go to
> Python 3 in the near future.
>

Backpatch might be no big deal. Let me see what I can do.

**Comment by mhagander** [comment]
It is definitely a common problem - ran into the same issue with barman a few weeks back: https://github.com/2ndquadrant-it/barman/commit/2936b35a7f62cbaa087c2641942aa70e359dd54b (so if you haven't already, you might want to look over that list and copy those excludes if there is something else you're missing).

**Comment by fdr** [comment]
8362eb815cd427b9b6bb09a2b421e9a276dbdce8
