### ISSUE TITLE
0.9.2 on Azure/WABS cannot list or delete recent backups

### ISSUE THREAD

**Issue by profilernz** [wal-e/wal-e#297]
Been using wal-e for 3 years on AWS with no issues, thanks for such a great tool.

But today I noticed something funny in our only Azure VM.
Running "backup-list" gives me:
Wed, 28 Sep 2016 12:16:29 GMT
...
Tue, 18 Oct 2016 12:18:09 GMT
as the oldest and lastest backups,
but Azure's Web UI clearly shows successful daily backups since that last one, including 2 done today (one of those performed manually, with no issues).
This also means that our "delete --confirm retain 21" is not doing anything since wal-e can't see anything past 18 Oct and backups have been piling up...

Running 0.9.2 on Centos 7, and as per @fdr's comments in https://github.com/wal-e/wal-e/issues/295 I gather you are willing to support 0.9.x users going forward? I tried upgrading to the latest version, but ran into python3 issues... Any pointers on where to go from here would be greatly appreciated... Thanks!

**Comment by fdr** [comment]
Do you think you might be affected by 1aaacc6f609ffedf51dabd8c280e2ea7b1ea51ef?

**Comment by fdr** [comment]
I will release crucial bug fixes for 0.9.x, but only if it's pretty impractical to fix things or work around in 1.x.

**Comment by profilernz** [comment]
Thanks.
I noticed the issuse mentioned in https://github.com/wal-e/wal-e/commit/1aaacc6f609ffedf51dabd8c280e2ea7b1ea51ef back in the day when we first started with Azure but it seemed mostly cosmetic so I marched on. I guess it could be related...
But Azure's UI seems to show all backups under the same directory level.
Should I just create a new/fresh WABS store and divert new backups there?

**Comment by fdr** [comment]
To cover our bases: did you upgrade WAL-E when this behavior started happening? Or did it start seemingly spontaneously?

**Comment by profilernz** [comment]
Spontaneously.
I think I'll spin up a test VM with python3 and the latest wal-e and test this WABS store from there.
Won't happen until early next week though, but I'll let you know as soon as I have some results.

**Comment by fdr** [comment]
On Wed, Nov 30, 2016 at 9:31 AM profilernz <notifications@github.com> wrote:

> Spontaneously.
> I think I'll spin up a test VM with python3 and the latest wal-e and test
> this WABS store from there.
> Won't happen until early next week though, but I'll let you know as soon
> as I have some results.
>
>
> Bizarre. Makes me wonder if there is a bug in paginating over the keys.

Let's see what happens with a new version, if you are willing to test it.

**Comment by profilernz** [comment]
OK, tested 1.0.1 with python 3.5, wal-e sees no backups whatsoever (using the exact same WABS credentials / blob store etc).

**Comment by profilernz** [comment]
We are leaving Azure soon (now that AWS does Canada), let me know if you'd like me to test this any further...

**Comment by fdr** [comment]
On Mon, Dec 12, 2016 at 11:37 AM profilernz <notifications@github.com>
wrote:

> We are leaving Azure soon (now that AWS does Canada), let me know if you'd
> like me to test this any further...
>

Interesting. Uh. Let's let the bug lie, though it is disturbing. I don't
think I have the time to treat your case to warrant making your move more
complex.

**Comment by profilernz** [comment]
Cool thanks.
