### ISSUE TITLE
archive_status

### ISSUE THREAD

**Issue by tblake84** [wal-e/wal-e#305]
Using PostgreSQL 9.3 and backup-push works just fine.  wal-push fails for not finding archive_status/ with the following error:

wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "wal-push".
        STRUCTURED: time=2016-12-20T18:53:23.533132-00 pid=7924
wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
        DETAIL: Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/wal_e/cmd.py", line 592, in main
            concurrency=args.pool_size)
          File "/usr/local/lib/python2.7/dist-packages/wal_e/operator/backup.py", line 275, in wal_archive
            other_segment = seg_stream.next()
          File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/pg/wal_transfer.py", line 70, in from_ready_archive_status
            statuses = os.listdir(status_dir)
        OSError: [Errno 2] No such file or directory: '/var/lib/postgresql/9.3/archive_status'

        STRUCTURED: time=2016-12-20T18:53:23.567602-00 pid=7924

Its looking in the wrong directory for archive_status.  It exists in /var/lib/postgresql/9.3/main/pg_xlog/archive_status.  Any ideas?

**Comment by fdr** [comment]
Are you somehow changing directory in in some wrapper script around WAL-E? It depends on `cwd` being a particular place.
