### ISSUE TITLE
Enable server side encryption in S3

### ISSUE THREAD

**Issue by lindenle** [wal-e/wal-e#338]
Is there a way to add `--sse` or `"x-amz-server-side-encryption": "AES256"`?

http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html

**Comment by perfectayush** [comment]
@lindenle Server Side encryption is on by default https://github.com/wal-e/wal-e/commit/9b6ede3eee74b98bb6187377ed42dc0a54ce5459

**Comment by lindenle** [comment]
Yep. Thanks!
