### ISSUE TITLE
SSL verification fails on a internal CA

### ISSUE THREAD

**Issue by onerikdawn** [wal-e/wal-e#345]
I have an openstack swift setup with an internal CA, I install this CA certificate on systems to avoid verification errors.
The swift client and other CLI tools like curl don't give an error with the certificate installed.

But wal-e has been failing to verify the ssl certificate from openstack swift.

Is there any way to temporarily disable the CA verification for wal-e?

I install the internal CA certificate on a debian system by copying it to `/usr/local/share/ca-certificates/` and running `update-ca-certificates `

**Comment by tschwaerzl** [comment]
SSL validation is integrated in `python-swiftclient`. We could pass `insecure=True` to bypass this.
https://docs.openstack.org/developer/python-swiftclient/swiftclient.html#swiftclient.client.Connection

You could add it on this file https://github.com/wal-e/wal-e/blob/master/wal_e/blobstore/swift/calling_format.py#L13 after Line 13 to test it.

**Comment by onerikdawn** [comment]
I think that would help for now.

**Comment by tschwaerzl** [comment]
And btw....AFAIK if you use `virtualenv` your ca-certificates will not be used. As described in the Swiftclient Docs you could also pass the CA-Certs and leave `insecure` as is to `False`.

But maybe I'm wrong with this one, never played with own CAs with IX clients.

**Comment by onerikdawn** [comment]
I think this issue is not related to wal-e since now i have noticed that swift client also has this certificate verification issue.

Could be related to urllib but i have not confirmed it yet since an another python application which does not use urllib didn't show this error.

**Comment by onerikdawn** [comment]
The problem was not urllib but since python is using [certifi](https://github.com/certifi/python-certifi/issues/22) that was causing the ssl error.
For now I have concatenated the the CA certificate to certifi bundle.
