### ISSUE TITLE
WAL file is from different database system: WAL file database system identifier is 6422218584094261886, pg_control database system identifier is 6338745400937582833

### ISSUE THREAD

**Issue by danielmwai** [wal-e/wal-e#350]
Am using WAL E and trying to restore a postgresql database i get the error  WAL file is from different database system: WAL file database system identifier is 6422218584094261886, pg_control database system identifier is 6338745400937582833

How can i force the postgresql database to use the database identifier of the WAL archive or force WAL archive to use the Database system identifier of the database

**Comment by fdr** [comment]
You are probably applying WAL between two distinct systems, which is not well defined and would cause corruption.

**Comment by andrewgy8** [comment]
@fdr Hmmm, interesting.  So you are saying that if my server gets wiped out and all data lost on that machine. Then spin up another server and try to `backup-fetch`, it wont work with that installation of postgres because its a distinct from the previous system?

**Comment by fdr** [comment]
`backup-fetch`ed databases should work, so long the WAL and the backup restored match. What I'm saying here is somehow you have a system that has a separate `initdb` that is attempting to replay WAL from a distinct system.

**Comment by andrewgy8** [comment]
Gotcha. And sure and behold if I restarted my entire backup process, with a new `back-up push` command the restore worked.   

As far as the backups go, it seems like the WAL files are pushed every minute or so according to my postgres.conf file, however the backup push command is only done every 24 hours. 

Does that seem right to you?
