### ISSUE TITLE
WALE_GS_PREFIX doesn't work

### ISSUE THREAD

**Issue by luannnh** [wal-e/wal-e#368]
Hi team, 

We are using WAL-E version **1.1.0b1** to archive WAL files to Google Storage.
_postgresql.conf_
```
archive_mode = on
archive_command = '/usr/local/bin/envdir /etc/wal-e.d/env /bin/wal-e wal-push %p'
archive_timeout = 60
```

And WALE_GS_PREFIX
```
cat /etc/wal-e.d/env/WALE_GS_PREFIX 
gs://int-fo-pgsql-rip/wal-e
```
**Issue**: WAL files was copying to `"gs:/int-fo-pgsql-rip/ /wal-e"`, **i.e. having a new folder name "/"** **before "wal-e" folder**

Please take a look at the issue.
Thank you.

**Comment by deverant** [comment]
This is a known issue and being worked on in #320.

The problem right now is that the current PR doesn't really handle backwards compatibility and even if it is fine to start uploading to a new directory without the extra forward slash, we would need a way to be able to restore from the old location.

**Comment by luannnh** [comment]
Thank you @deverant .
