### ISSUE TITLE
Mark this repo as DEPRECATED/OBSOLETE!!!

### ISSUE THREAD

**Issue by hatharom** [wal-e/wal-e#429]
I have struggled with this repository for hours just to find out that it is completly abandoned in the favor of https://github.com/wal-g/wal-g.

Wal-E documentation mentions nothing about this!! Pretty annoying...

The documention **SHOULD**  start with the information that it is no longer maintained.

**Comment by frafra** [comment]
@fdr Could you mark this repo as obsolete, please?

**Comment by fdr** [comment]
Alright, I'll do something about that. That said, I do still wind up using it from time to time without issue. I wouldn't put new stuff on it though. What happened?

**Comment by fdr** [comment]
I did it. https://github.com/wal-e/wal-e/commit/f5b3e790fe10daa098b8cbf01d836c4885dc13c7
