### ISSUE TITLE
Is Postgres 10+ supported at all?

### ISSUE THREAD

**Issue by calebwoofenden** [wal-e/wal-e#434]
I am working on upgrading an old Postgres 9.6 cluster to Postgres 14. I did the pg_upgrade without issues, but when trying to run `wal-e backup-push` I get this error:

```
ERROR:  function pg_xlogfile_name_offset(pg_lsn) does not exist
LINE 1: ...ad(file_offset::text, 8, '0') AS file_offset FROM pg_xlogfil...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

According to [one source](https://www.postgresql.org/message-id/CAKJS1f_6CBr03kgbqeRDCg6P4Ei5pGrdALUxsW9L1TzmPs%2BHzA%40mail.gmail.com), this function was renamed to `pg_current_wal_lsn` in Postgres 10. Does this just mean that PG10+ is not supported by WAL-E?

**Comment by fdr** [comment]
There was a big rename to get rid of `xlog` for `wal` at some point, I never taught WAL-E compatibility for it. If you need something that's almost like a drop-in replacement, I suggest WAL-G. It can read WAL-E archives, fact.

**Comment by calebwoofenden** [comment]
Thanks @fdr , I saw that wal-g is an easy replacement and I've been working on replacing our wal-e usage with wal-g. It's helpful to know that wal-e definitely won't work for us on pg10+ though.
