### ISSUE TITLE
wal-e can't find base backup on live server after upload

### ISSUE THREAD

**Issue by micahhausler** [wal-e/wal-e#7]
I'm running Postgres 9.1 on Ubuntu 12.04 and using the latest version of wal-e (0.5.12) and can't get a base backup to be found after upload.

I'm using the setup described in the README with envdir for my AWS credentials and S3 bucket name, and can get the WAL to upload to S3 and the backup appears to work correctly.

My last .backup pg_xlog file looks like this:

```
START WAL LOCATION: 185/7FE8B9A8 (file 00000001000001850000007F)
STOP WAL LOCATION: 185/C747F3E8 (file 0000000100000185000000C7)
CHECKPOINT LOCATION: 185/82513A38
BACKUP METHOD: pg_start_backup
START TIME: 2013-04-15 21:02:50 UTC
LABEL: freeze_start_2013-04-15T20:44:53.887145+00:00
STOP TIME: 2013-04-16 01:41:50 UTC
```

I checked the S3 Bucket and all the tar_archive files are there, but wal-e seems unable to find that backup. When I perform a `envdir /etc/wal-e.d/env wal-e backup-list`, all I get is the CSV headers and no backups are found. This is the case on the master and slave servers.

I had this issue in a testing environment and it only seemed that my backups could be found if I did an initial `wal-e backup-push` with the `--while-offline` flag. Subsequent test environment backups were found, but the initial couldn't be found without the offline flag. 

I'd like to use wal-e in production, but can't afford to have my production database off for hours just to get a base backup. Any help is much appreciated.

**Comment by eduherraiz** [comment]
I reproduce this problem today, the problem was the backup fill the /tmp volume.
I hope this comment will be useful for someone!
